insert into garages (id, adresse, code_postal) values (1, '88 Fairfield Avenue', null);
insert into garages (id, adresse, code_postal) values (2, '805 Sunbrook Court', null);
insert into garages (id, adresse, code_postal) values (3, '72 Sommers Junction', '4234');
insert into garages (id, adresse, code_postal) values (4, '9 Thompson Terrace', '93321 CEDEX');
insert into garages (id, adresse, code_postal) values (5, '02160 Merchant Avenue', null);
insert into garages (id, adresse, code_postal) values (6, '34 Kenwood Terrace', null);
insert into garages (id, adresse, code_postal) values (7, '8646 Service Junction', '32500-000');
insert into garages (id, adresse, code_postal) values (8, '78695 Cherokee Trail', null);
insert into garages (id, adresse, code_postal) values (9, '8 Michigan Circle', null);
insert into garages (id, adresse, code_postal) values (10, '4 Dovetail Plaza', null);
insert into garages (id, adresse, code_postal) values (11, '8352 Delladonna Alley', null);
insert into garages (id, adresse, code_postal) values (12, '4 Hauk Alley', '4860-352');
insert into garages (id, adresse, code_postal) values (13, '885 Grim Circle', '581 15');
insert into garages (id, adresse, code_postal) values (14, '52 Mallory Pass', null);
insert into garages (id, adresse, code_postal) values (15, '4435 Trailsway Trail', '4506');
insert into garages (id, adresse, code_postal) values (16, '4394 Marcy Street', null);
insert into garages (id, adresse, code_postal) values (17, '439 Florence Avenue', null);
insert into garages (id, adresse, code_postal) values (18, '4 Corry Place', null);
insert into garages (id, adresse, code_postal) values (19, '35393 7th Road', null);
insert into garages (id, adresse, code_postal) values (20, '00532 Ridge Oak Place', '545 30');
insert into garages (id, adresse, code_postal) values (21, '0 Kim Crossing', '2765-184');
insert into garages (id, adresse, code_postal) values (22, '09632 Lakewood Avenue', null);
insert into garages (id, adresse, code_postal) values (23, '37282 Burrows Trail', null);
insert into garages (id, adresse, code_postal) values (24, '92 Nova Avenue', '880-2215');
insert into garages (id, adresse, code_postal) values (25, '3 Commercial Trail', null);
insert into garages (id, adresse, code_postal) values (26, '4673 Truax Lane', null);
insert into garages (id, adresse, code_postal) values (27, '6 Maryland Parkway', null);
insert into garages (id, adresse, code_postal) values (28, '356 Atwood Street', null);
insert into garages (id, adresse, code_postal) values (29, '2632 Reindahl Junction', '35047 CEDEX 9');
insert into garages (id, adresse, code_postal) values (30, '9 Kings Trail', '674480');
insert into garages (id, adresse, code_postal) values (31, '8 Independence Plaza', null);
insert into garages (id, adresse, code_postal) values (32, '2762 Pond Point', '19900-000');
insert into garages (id, adresse, code_postal) values (33, '74 Northfield Hill', '10208');
insert into garages (id, adresse, code_postal) values (34, '9389 Meadow Vale Center', '84204 CEDEX');
insert into garages (id, adresse, code_postal) values (35, '81347 Talisman Circle', null);
insert into garages (id, adresse, code_postal) values (36, '276 Starling Parkway', null);
insert into garages (id, adresse, code_postal) values (37, '75 Talisman Lane', null);
insert into garages (id, adresse, code_postal) values (38, '42 Leroy Street', '231048');
insert into garages (id, adresse, code_postal) values (39, '2050 Claremont Plaza', '0204');
insert into garages (id, adresse, code_postal) values (40, '3645 Brickson Park Point', '40053');
insert into garages (id, adresse, code_postal) values (41, '6512 Cambridge Avenue', '43-245');
insert into garages (id, adresse, code_postal) values (42, '604 Oriole Park', null);
insert into garages (id, adresse, code_postal) values (43, '1246 Jenifer Trail', null);
insert into garages (id, adresse, code_postal) values (44, '3414 Thackeray Pass', '346930');
insert into garages (id, adresse, code_postal) values (45, '2764 Hanover Avenue', null);
insert into garages (id, adresse, code_postal) values (46, '40428 Trailsway Crossing', '332 04');
insert into garages (id, adresse, code_postal) values (47, '4 Tennyson Plaza', null);
insert into garages (id, adresse, code_postal) values (48, '2313 Dahle Plaza', '2785-549');
insert into garages (id, adresse, code_postal) values (49, '582 Birchwood Hill', null);
insert into garages (id, adresse, code_postal) values (50, '8491 Amoth Center', null);
insert into garages (id, adresse, code_postal) values (51, '23 Longview Court', '97-280');
insert into garages (id, adresse, code_postal) values (52, '57581 Crescent Oaks Court', null);
insert into garages (id, adresse, code_postal) values (53, '8583 Eggendart Court', null);
insert into garages (id, adresse, code_postal) values (54, '076 Upham Road', '7405');
insert into garages (id, adresse, code_postal) values (55, '0709 Onsgard Parkway', null);
insert into garages (id, adresse, code_postal) values (56, '515 Steensland Crossing', '5145');
insert into garages (id, adresse, code_postal) values (57, '93865 Ohio Junction', '40602');
insert into garages (id, adresse, code_postal) values (58, '538 Kedzie Road', '445 33');
insert into garages (id, adresse, code_postal) values (59, '32523 Schlimgen Way', '27-630');
insert into garages (id, adresse, code_postal) values (60, '7 Manley Terrace', null);
insert into garages (id, adresse, code_postal) values (61, '15 Burrows Place', null);
insert into garages (id, adresse, code_postal) values (62, '47914 Atwood Center', '1033');
insert into garages (id, adresse, code_postal) values (63, '18148 Stephen Way', null);
insert into garages (id, adresse, code_postal) values (64, '840 Algoma Parkway', null);
insert into garages (id, adresse, code_postal) values (65, '77 Longview Pass', null);
insert into garages (id, adresse, code_postal) values (66, '096 Lawn Court', '79960');
insert into garages (id, adresse, code_postal) values (67, '83963 Sycamore Court', '98833');
insert into garages (id, adresse, code_postal) values (68, '45972 Grayhawk Court', null);
insert into garages (id, adresse, code_postal) values (69, '37 Myrtle Court', '1805');
insert into garages (id, adresse, code_postal) values (70, '95148 Pond Avenue', '1110');
insert into garages (id, adresse, code_postal) values (71, '7179 Dayton Street', '5947');
insert into garages (id, adresse, code_postal) values (72, '171 Scofield Plaza', '13409');
insert into garages (id, adresse, code_postal) values (73, '08714 Nancy Junction', null);
insert into garages (id, adresse, code_postal) values (74, '5 Grayhawk Center', null);
insert into garages (id, adresse, code_postal) values (75, '507 Randy Street', '75104 CEDEX 02');
insert into garages (id, adresse, code_postal) values (76, '1939 Buell Park', null);
insert into garages (id, adresse, code_postal) values (77, '7 Linden Alley', '30112 CEDEX');
insert into garages (id, adresse, code_postal) values (78, '06763 Beilfuss Parkway', null);
insert into garages (id, adresse, code_postal) values (79, '0 Loomis Hill', '686029');
insert into garages (id, adresse, code_postal) values (80, '31 1st Road', null);
insert into garages (id, adresse, code_postal) values (81, '63685 Artisan Court', null);
insert into garages (id, adresse, code_postal) values (82, '93 Golf View Street', '04380');
insert into garages (id, adresse, code_postal) values (83, '07557 Mesta Road', '1170');
insert into garages (id, adresse, code_postal) values (84, '67846 John Wall Hill', null);
insert into garages (id, adresse, code_postal) values (85, '688 Shoshone Terrace', null);
insert into garages (id, adresse, code_postal) values (86, '05 Graceland Terrace', null);
insert into garages (id, adresse, code_postal) values (87, '5300 Hollow Ridge Avenue', '694903');
insert into garages (id, adresse, code_postal) values (88, '22 Lukken Avenue', '432980');
insert into garages (id, adresse, code_postal) values (89, '3912 Iowa Alley', 'K7S');
insert into garages (id, adresse, code_postal) values (90, '96 Canary Avenue', '357 03');
insert into garages (id, adresse, code_postal) values (91, '5451 Thompson Pass', null);
insert into garages (id, adresse, code_postal) values (92, '5015 Annamark Drive', null);
insert into garages (id, adresse, code_postal) values (93, '3 Corben Crossing', '15385-000');
insert into garages (id, adresse, code_postal) values (94, '63 Bobwhite Center', null);
insert into garages (id, adresse, code_postal) values (95, '6698 3rd Center', '435 84');
insert into garages (id, adresse, code_postal) values (96, '58481 Autumn Leaf Alley', '675 01');
insert into garages (id, adresse, code_postal) values (97, '32 Jay Alley', '94518 CEDEX 1');
insert into garages (id, adresse, code_postal) values (98, '2811 Waxwing Terrace', null);
insert into garages (id, adresse, code_postal) values (99, '18 Novick Trail', null);
insert into garages (id, adresse, code_postal) values (100, '74 Doe Crossing Pass', '6276');
insert into garages (id, adresse, code_postal) values (101, '0614 Hudson Center', '55530');
insert into garages (id, adresse, code_postal) values (102, '05 Roxbury Circle', '434 95');
insert into garages (id, adresse, code_postal) values (103, '4074 International Road', '141662');
insert into garages (id, adresse, code_postal) values (104, '746 Eagan Park', null);
insert into garages (id, adresse, code_postal) values (105, '472 Mosinee Trail', null);
insert into garages (id, adresse, code_postal) values (106, '400 Fairview Park', null);
insert into garages (id, adresse, code_postal) values (107, '7648 Dexter Terrace', null);
insert into garages (id, adresse, code_postal) values (108, '75 Harbort Alley', '90045');
insert into garages (id, adresse, code_postal) values (109, '98481 David Trail', null);
insert into garages (id, adresse, code_postal) values (110, '126 Crest Line Place', null);
insert into garages (id, adresse, code_postal) values (111, '418 Grover Pass', '31410');
insert into garages (id, adresse, code_postal) values (112, '2 Coleman Parkway', '73028');
insert into garages (id, adresse, code_postal) values (113, '50695 Everett Crossing', null);
insert into garages (id, adresse, code_postal) values (114, '65303 Riverside Drive', null);
insert into garages (id, adresse, code_postal) values (115, '98026 Sutherland Drive', null);
insert into garages (id, adresse, code_postal) values (116, '799 Heffernan Avenue', '9001');
insert into garages (id, adresse, code_postal) values (117, '86183 Calypso Street', '8424');
insert into garages (id, adresse, code_postal) values (118, '174 Village Green Avenue', '3600-587');
insert into garages (id, adresse, code_postal) values (119, '49078 Meadow Ridge Trail', null);
insert into garages (id, adresse, code_postal) values (120, '9 Loomis Hill', null);
insert into garages (id, adresse, code_postal) values (121, '65215 Dexter Hill', null);
insert into garages (id, adresse, code_postal) values (122, '19352 Moulton Court', 'K7A');
insert into garages (id, adresse, code_postal) values (123, '7 Daystar Trail', null);
insert into garages (id, adresse, code_postal) values (124, '7635 Burrows Parkway', '4220');
insert into garages (id, adresse, code_postal) values (125, '11227 Basil Terrace', null);
insert into garages (id, adresse, code_postal) values (126, '527 Caliangt Place', null);
insert into garages (id, adresse, code_postal) values (127, '57 Waubesa Terrace', null);
insert into garages (id, adresse, code_postal) values (128, '88 Fulton Alley', '77493');
insert into garages (id, adresse, code_postal) values (129, '21370 Sunfield Trail', '77915-000');
insert into garages (id, adresse, code_postal) values (130, '53289 Becker Drive', 'J0J');
insert into garages (id, adresse, code_postal) values (131, '00 Westerfield Place', '3460');
insert into garages (id, adresse, code_postal) values (132, '713 Schiller Road', null);
insert into garages (id, adresse, code_postal) values (133, '50189 Carpenter Crossing', null);
insert into garages (id, adresse, code_postal) values (134, '86 Park Meadow Place', null);
insert into garages (id, adresse, code_postal) values (135, '472 Thierer Way', '48000-000');
insert into garages (id, adresse, code_postal) values (136, '6 Mifflin Crossing', null);
insert into garages (id, adresse, code_postal) values (137, '6 Dottie Park', '664 62');
insert into garages (id, adresse, code_postal) values (138, '4 Manufacturers Junction', '5050-365');
insert into garages (id, adresse, code_postal) values (139, '108 Scofield Crossing', null);
insert into garages (id, adresse, code_postal) values (140, '58 Farragut Way', null);
insert into garages (id, adresse, code_postal) values (141, '9 Emmet Parkway', '87630-000');
insert into garages (id, adresse, code_postal) values (142, '6623 Mayer Point', null);
insert into garages (id, adresse, code_postal) values (143, '3632 Reinke Crossing', null);
insert into garages (id, adresse, code_postal) values (144, '7254 Truax Park', null);
insert into garages (id, adresse, code_postal) values (145, '808 Mifflin Point', null);
insert into garages (id, adresse, code_postal) values (146, '172 Bay Trail', '14910-000');
insert into garages (id, adresse, code_postal) values (147, '26340 Clove Trail', null);
insert into garages (id, adresse, code_postal) values (148, '5480 Dottie Circle', '141986');
insert into garages (id, adresse, code_postal) values (149, '8641 Gerald Lane', '408-0021');
insert into garages (id, adresse, code_postal) values (150, '7426 Dexter Street', '3119');
insert into garages (id, adresse, code_postal) values (151, '972 Service Lane', null);
insert into garages (id, adresse, code_postal) values (152, '6 Trailsway Parkway', '351 06');
insert into garages (id, adresse, code_postal) values (153, '84 Anniversary Point', '741-0062');
insert into garages (id, adresse, code_postal) values (154, '83158 Bashford Park', null);
insert into garages (id, adresse, code_postal) values (155, '5956 Londonderry Pass', '241551');
insert into garages (id, adresse, code_postal) values (156, '1395 Emmet Pass', '22301');
insert into garages (id, adresse, code_postal) values (157, '5319 Redwing Center', '28210');
insert into garages (id, adresse, code_postal) values (158, '7550 Shopko Junction', null);
insert into garages (id, adresse, code_postal) values (159, '83 Carioca Park', null);
insert into garages (id, adresse, code_postal) values (160, '56 Comanche Street', '4615-310');
insert into garages (id, adresse, code_postal) values (161, '0399 Moulton Drive', null);
insert into garages (id, adresse, code_postal) values (162, '3 Service Pass', '11-210');
insert into garages (id, adresse, code_postal) values (163, '20 Charing Cross Court', null);
insert into garages (id, adresse, code_postal) values (164, '88 Kropf Place', '11-042');
insert into garages (id, adresse, code_postal) values (165, '954 Hanover Junction', '357373');
insert into garages (id, adresse, code_postal) values (166, '0 Onsgard Circle', '113 80');
insert into garages (id, adresse, code_postal) values (167, '7 Logan Trail', null);
insert into garages (id, adresse, code_postal) values (168, '1032 Butternut Plaza', '442710');
insert into garages (id, adresse, code_postal) values (169, '259 Meadow Ridge Terrace', '5705');
insert into garages (id, adresse, code_postal) values (170, '60165 Rutledge Lane', '7150-366');
insert into garages (id, adresse, code_postal) values (171, '00 Muir Pass', null);
insert into garages (id, adresse, code_postal) values (172, '47336 Prairieview Court', '768 21');
insert into garages (id, adresse, code_postal) values (173, '19 Ohio Street', null);
insert into garages (id, adresse, code_postal) values (174, '67420 Blue Bill Park Street', null);
insert into garages (id, adresse, code_postal) values (175, '99 Mayfield Hill', null);
insert into garages (id, adresse, code_postal) values (176, '06 Hovde Junction', '87900');
insert into garages (id, adresse, code_postal) values (177, '94481 Truax Circle', '84-242');
insert into garages (id, adresse, code_postal) values (178, '4 Summerview Parkway', null);
insert into garages (id, adresse, code_postal) values (179, '62 Lotheville Street', null);
insert into garages (id, adresse, code_postal) values (180, '2930 Brickson Park Park', '83553');
insert into garages (id, adresse, code_postal) values (181, '68696 Lien Center', null);
insert into garages (id, adresse, code_postal) values (182, '91663 Rusk Point', '687 12');
insert into garages (id, adresse, code_postal) values (183, '6 Pennsylvania Plaza', null);
insert into garages (id, adresse, code_postal) values (184, '0811 Holy Cross Terrace', 'DT10');
insert into garages (id, adresse, code_postal) values (185, '74062 Mesta Circle', null);
insert into garages (id, adresse, code_postal) values (186, '508 Grasskamp Hill', '05-319');
insert into garages (id, adresse, code_postal) values (187, '161 Gale Park', '79042 CEDEX 9');
insert into garages (id, adresse, code_postal) values (188, '1 Arkansas Terrace', null);
insert into garages (id, adresse, code_postal) values (189, '91968 Nelson Road', '368034');
insert into garages (id, adresse, code_postal) values (190, '12 Sugar Way', '309135');
insert into garages (id, adresse, code_postal) values (191, '673 Sherman Pass', '44-280');
insert into garages (id, adresse, code_postal) values (192, '3 Bay Park', null);
insert into garages (id, adresse, code_postal) values (193, '9 Golf Course Lane', '93612');
insert into garages (id, adresse, code_postal) values (194, '56 Cody Junction', '349-1104');
insert into garages (id, adresse, code_postal) values (195, '5404 Lukken Pass', null);
insert into garages (id, adresse, code_postal) values (196, '19909 Brentwood Plaza', null);
insert into garages (id, adresse, code_postal) values (197, '5787 Carberry Point', '7600-314');
insert into garages (id, adresse, code_postal) values (198, '51 Debs Court', '124 76');
insert into garages (id, adresse, code_postal) values (199, '91146 Morning Center', null);
insert into garages (id, adresse, code_postal) values (200, '912 Darwin Avenue', null);
insert into garages (id, adresse, code_postal) values (201, '74 Corry Avenue', '4810-050');
insert into garages (id, adresse, code_postal) values (202, '8 Dawn Street', '144010');
insert into garages (id, adresse, code_postal) values (203, '059 Reindahl Trail', null);
insert into garages (id, adresse, code_postal) values (204, '5797 Hallows Place', null);
insert into garages (id, adresse, code_postal) values (205, '70 Susan Pass', '76210');
insert into garages (id, adresse, code_postal) values (206, '7840 Lake View Point', null);
insert into garages (id, adresse, code_postal) values (207, '03138 Continental Plaza', null);
insert into garages (id, adresse, code_postal) values (208, '67 Rusk Trail', '3210');
insert into garages (id, adresse, code_postal) values (209, '9 Darwin Street', '55572');
insert into garages (id, adresse, code_postal) values (210, '4495 Beilfuss Drive', '4595-414');
insert into garages (id, adresse, code_postal) values (211, '59 Northland Way', '5417');
insert into garages (id, adresse, code_postal) values (212, '88900 North Court', null);
insert into garages (id, adresse, code_postal) values (213, '860 5th Avenue', '64029 CEDEX 9');
insert into garages (id, adresse, code_postal) values (214, '136 Lakewood Gardens Circle', null);
insert into garages (id, adresse, code_postal) values (215, '3456 Packers Center', null);
insert into garages (id, adresse, code_postal) values (216, '1407 Milwaukee Place', null);
insert into garages (id, adresse, code_postal) values (217, '80458 Dorton Trail', '22120');
insert into garages (id, adresse, code_postal) values (218, '6294 Weeping Birch Drive', null);
insert into garages (id, adresse, code_postal) values (219, '8644 Sherman Court', null);
insert into garages (id, adresse, code_postal) values (220, '728 Maple Center', null);
insert into garages (id, adresse, code_postal) values (221, '01655 Gina Parkway', null);
insert into garages (id, adresse, code_postal) values (222, '2930 Summerview Terrace', '56199');
insert into garages (id, adresse, code_postal) values (223, '3 American Ash Point', '742-2807');
insert into garages (id, adresse, code_postal) values (224, '570 New Castle Park', '2302');
insert into garages (id, adresse, code_postal) values (225, '57 Muir Junction', '747 33');
insert into garages (id, adresse, code_postal) values (226, '966 Ludington Street', '612 32');
insert into garages (id, adresse, code_postal) values (227, '62971 Kingsford Trail', null);
insert into garages (id, adresse, code_postal) values (228, '0 Crowley Plaza', null);
insert into garages (id, adresse, code_postal) values (229, '5 5th Crossing', null);
insert into garages (id, adresse, code_postal) values (230, '924 8th Street', '6100');
insert into garages (id, adresse, code_postal) values (231, '3428 Doe Crossing Terrace', null);
insert into garages (id, adresse, code_postal) values (232, '5642 Cardinal Parkway', null);
insert into garages (id, adresse, code_postal) values (233, '049 Roxbury Alley', null);
insert into garages (id, adresse, code_postal) values (234, '29757 Carioca Point', null);
insert into garages (id, adresse, code_postal) values (235, '540 Vermont Trail', '32900-000');
insert into garages (id, adresse, code_postal) values (236, '207 Anhalt Crossing', '77045');
insert into garages (id, adresse, code_postal) values (237, '9846 Banding Avenue', null);
insert into garages (id, adresse, code_postal) values (238, '69 Forster Street', 'K36');
insert into garages (id, adresse, code_postal) values (239, '5734 Forest Dale Lane', '142817');
insert into garages (id, adresse, code_postal) values (240, '2570 Pepper Wood Place', null);
insert into garages (id, adresse, code_postal) values (241, '69 Independence Plaza', null);
insert into garages (id, adresse, code_postal) values (242, '77904 Marcy Crossing', null);
insert into garages (id, adresse, code_postal) values (243, '59069 Northridge Terrace', null);
insert into garages (id, adresse, code_postal) values (244, '81737 Northport Park', null);
insert into garages (id, adresse, code_postal) values (245, '08 Bayside Alley', null);
insert into garages (id, adresse, code_postal) values (246, '37233 Saint Paul Terrace', null);
insert into garages (id, adresse, code_postal) values (247, '7138 Redwing Street', '3025-353');
insert into garages (id, adresse, code_postal) values (248, '857 Merchant Hill', null);
insert into garages (id, adresse, code_postal) values (249, '4 Sunfield Place', '346580');
insert into garages (id, adresse, code_postal) values (250, '3870 Mcbride Plaza', 'D15');
insert into garages (id, adresse, code_postal) values (251, '17063 Parkside Road', null);
insert into garages (id, adresse, code_postal) values (252, '020 Sage Court', null);
insert into garages (id, adresse, code_postal) values (253, '700 Emmet Place', null);
insert into garages (id, adresse, code_postal) values (254, '329 Kim Junction', null);
insert into garages (id, adresse, code_postal) values (255, '5 Ridgeview Drive', '931 52');
insert into garages (id, adresse, code_postal) values (256, '729 Spaight Center', '11024');
insert into garages (id, adresse, code_postal) values (257, '3 Glendale Lane', '7032');
insert into garages (id, adresse, code_postal) values (258, '96 Grover Drive', '7780-256');
insert into garages (id, adresse, code_postal) values (259, '59578 Redwing Avenue', '417088');
insert into garages (id, adresse, code_postal) values (260, '03 Green Ridge Avenue', null);
insert into garages (id, adresse, code_postal) values (261, '7569 Eagle Crest Trail', null);
insert into garages (id, adresse, code_postal) values (262, '383 Del Mar Alley', null);
insert into garages (id, adresse, code_postal) values (263, '0 Buell Place', '538 03');
insert into garages (id, adresse, code_postal) values (264, '9537 Algoma Parkway', null);
insert into garages (id, adresse, code_postal) values (265, '9636 Drewry Alley', '453002');
insert into garages (id, adresse, code_postal) values (266, '3 Hazelcrest Circle', '79500-000');
insert into garages (id, adresse, code_postal) values (267, '76623 Reinke Point', '356003');
insert into garages (id, adresse, code_postal) values (268, '49 Kipling Way', null);
insert into garages (id, adresse, code_postal) values (269, '8936 Quincy Trail', '17120-000');
insert into garages (id, adresse, code_postal) values (270, '2286 Rowland Circle', null);
insert into garages (id, adresse, code_postal) values (271, '848 New Castle Trail', null);
insert into garages (id, adresse, code_postal) values (272, '81532 Loeprich Road', null);
insert into garages (id, adresse, code_postal) values (273, '9 Fieldstone Point', '54730');
insert into garages (id, adresse, code_postal) values (274, '338 Morningstar Road', '472 01');
insert into garages (id, adresse, code_postal) values (275, '121 Meadow Ridge Parkway', null);
insert into garages (id, adresse, code_postal) values (276, '13689 Shopko Lane', null);
insert into garages (id, adresse, code_postal) values (277, '84 Mandrake Crossing', null);
insert into garages (id, adresse, code_postal) values (278, '68713 Mcbride Trail', null);
insert into garages (id, adresse, code_postal) values (279, '6363 Cherokee Place', null);
insert into garages (id, adresse, code_postal) values (280, '7 Ludington Court', null);
insert into garages (id, adresse, code_postal) values (281, '5 Dapin Circle', null);
insert into garages (id, adresse, code_postal) values (282, '11472 High Crossing Pass', null);
insert into garages (id, adresse, code_postal) values (283, '570 Twin Pines Circle', '74004 CEDEX');
insert into garages (id, adresse, code_postal) values (284, '8476 Miller Junction', '4770-565');
insert into garages (id, adresse, code_postal) values (285, '4 Kinsman Alley', '44265 CEDEX 2');
insert into garages (id, adresse, code_postal) values (286, '67859 Portage Park', null);
insert into garages (id, adresse, code_postal) values (287, '71450 Crowley Junction', null);
insert into garages (id, adresse, code_postal) values (288, '3 Bayside Terrace', '18351');
insert into garages (id, adresse, code_postal) values (289, '047 Buena Vista Lane', '690922');
insert into garages (id, adresse, code_postal) values (290, '15 Arkansas Circle', null);
insert into garages (id, adresse, code_postal) values (291, '6 Milwaukee Lane', '32560');
insert into garages (id, adresse, code_postal) values (292, '3901 Spaight Alley', '97755-000');
insert into garages (id, adresse, code_postal) values (293, '0250 Sage Park', null);
insert into garages (id, adresse, code_postal) values (294, '478 Hoepker Crossing', null);
insert into garages (id, adresse, code_postal) values (295, '36 Miller Point', null);
insert into garages (id, adresse, code_postal) values (296, '57257 Lawn Street', '591 46');
insert into garages (id, adresse, code_postal) values (297, '09053 Reinke Road', null);
insert into garages (id, adresse, code_postal) values (298, '57 Arkansas Court', null);
insert into garages (id, adresse, code_postal) values (299, '73532 Forest Place', null);
insert into garages (id, adresse, code_postal) values (300, '59 Harper Way', '2855-609');
