insert into voitures (id, marque, modele, annee, garage_id) values (1, 'Chrysler', 'Sebring', 1996, 113);
insert into voitures (id, marque, modele, annee, garage_id) values (2, 'Honda', 'Accord', 1989, 88);
insert into voitures (id, marque, modele, annee, garage_id) values (3, 'Maybach', '57', 2009, 85);
insert into voitures (id, marque, modele, annee, garage_id) values (4, 'Chevrolet', 'Aveo', 2005, 38);
insert into voitures (id, marque, modele, annee, garage_id) values (5, 'Jaguar', 'XJ Series', 1999, 82);
insert into voitures (id, marque, modele, annee, garage_id) values (6, 'Honda', 'Accord', 1996, 83);
insert into voitures (id, marque, modele, annee, garage_id) values (7, 'Mercedes-Benz', 'SLK-Class', 2004, 194);
insert into voitures (id, marque, modele, annee, garage_id) values (8, 'Saturn', 'Outlook', 2008, 177);
insert into voitures (id, marque, modele, annee, garage_id) values (9, 'Pontiac', 'Bonneville', 1996, 173);
insert into voitures (id, marque, modele, annee, garage_id) values (10, 'Lincoln', 'Continental', 1994, 215);
insert into voitures (id, marque, modele, annee, garage_id) values (11, 'Ford', 'Taurus', 1995, 266);
insert into voitures (id, marque, modele, annee, garage_id) values (12, 'Lamborghini', 'Diablo', 1993, 39);
insert into voitures (id, marque, modele, annee, garage_id) values (13, 'Ford', 'Tempo', 1987, 176);
insert into voitures (id, marque, modele, annee, garage_id) values (14, 'Geo', 'Metro', 1994, 271);
insert into voitures (id, marque, modele, annee, garage_id) values (15, 'GMC', 'Savana 2500', 2001, 80);
insert into voitures (id, marque, modele, annee, garage_id) values (16, 'Aston Martin', 'Vantage', 2006, 117);
insert into voitures (id, marque, modele, annee, garage_id) values (17, 'Bentley', 'Continental GT', 2008, 272);
insert into voitures (id, marque, modele, annee, garage_id) values (18, 'Saab', '900', 1994, 117);
insert into voitures (id, marque, modele, annee, garage_id) values (19, 'Pontiac', 'Bonneville', 1991, 160);
insert into voitures (id, marque, modele, annee, garage_id) values (20, 'Volvo', 'C70', 1999, 73);
insert into voitures (id, marque, modele, annee, garage_id) values (21, 'Pontiac', 'Bonneville', 1985, 132);
insert into voitures (id, marque, modele, annee, garage_id) values (22, 'Audi', 'A6', 2003, 229);
insert into voitures (id, marque, modele, annee, garage_id) values (23, 'Mercury', 'Milan', 2008, 149);
insert into voitures (id, marque, modele, annee, garage_id) values (24, 'Volkswagen', 'Tiguan', 2011, 197);
insert into voitures (id, marque, modele, annee, garage_id) values (25, 'Lincoln', 'Navigator', 2010, 271);
insert into voitures (id, marque, modele, annee, garage_id) values (26, 'Pontiac', 'Vibe', 2010, 258);
insert into voitures (id, marque, modele, annee, garage_id) values (27, 'Chevrolet', 'Express', 2009, 56);
insert into voitures (id, marque, modele, annee, garage_id) values (28, 'Pontiac', 'Grand Prix', 1984, 65);
insert into voitures (id, marque, modele, annee, garage_id) values (29, 'Toyota', 'Sienna', 2000, 32);
insert into voitures (id, marque, modele, annee, garage_id) values (30, 'Cadillac', 'DTS', 2008, 300);
insert into voitures (id, marque, modele, annee, garage_id) values (31, 'Ford', 'Contour', 1997, 245);
insert into voitures (id, marque, modele, annee, garage_id) values (32, 'Lincoln', 'Continental', 1990, 270);
insert into voitures (id, marque, modele, annee, garage_id) values (33, 'Dodge', 'Caliber', 2011, 162);
insert into voitures (id, marque, modele, annee, garage_id) values (34, 'Volvo', 'V70', 2000, 111);
insert into voitures (id, marque, modele, annee, garage_id) values (35, 'Dodge', 'Viper', 2002, 176);
insert into voitures (id, marque, modele, annee, garage_id) values (36, 'Maserati', 'GranTurismo', 2010, 129);
insert into voitures (id, marque, modele, annee, garage_id) values (37, 'Dodge', 'Avenger', 1995, 137);
insert into voitures (id, marque, modele, annee, garage_id) values (38, 'Mazda', 'Miata MX-5', 1999, 285);
insert into voitures (id, marque, modele, annee, garage_id) values (39, 'Toyota', 'Matrix', 2011, 132);
insert into voitures (id, marque, modele, annee, garage_id) values (40, 'Mercedes-Benz', 'SL-Class', 1996, 298);
insert into voitures (id, marque, modele, annee, garage_id) values (41, 'Mazda', 'Protege', 1999, 220);
insert into voitures (id, marque, modele, annee, garage_id) values (42, 'BMW', '3 Series', 2011, 85);
insert into voitures (id, marque, modele, annee, garage_id) values (43, 'Dodge', 'Caravan', 1999, 97);
insert into voitures (id, marque, modele, annee, garage_id) values (44, 'Mitsubishi', 'Lancer Evolution', 2002, 292);
insert into voitures (id, marque, modele, annee, garage_id) values (45, 'GMC', 'Suburban 2500', 1992, 231);
insert into voitures (id, marque, modele, annee, garage_id) values (46, 'Toyota', 'T100', 1994, 219);
insert into voitures (id, marque, modele, annee, garage_id) values (47, 'Chevrolet', 'Tahoe', 2001, 300);
insert into voitures (id, marque, modele, annee, garage_id) values (48, 'Volkswagen', 'rio', 1997, 231);
insert into voitures (id, marque, modele, annee, garage_id) values (49, 'Mazda', 'CX-9', 2011, 233);
insert into voitures (id, marque, modele, annee, garage_id) values (50, 'Fiat', 'Nuova 500', 2012, 2);
insert into voitures (id, marque, modele, annee, garage_id) values (51, 'Mercedes-Benz', 'E-Class', 1987, 178);
insert into voitures (id, marque, modele, annee, garage_id) values (52, 'Jeep', 'Compass', 2010, 172);
insert into voitures (id, marque, modele, annee, garage_id) values (53, 'Honda', 'Prelude', 1992, 75);
insert into voitures (id, marque, modele, annee, garage_id) values (54, 'Chrysler', 'Sebring', 1997, 132);
insert into voitures (id, marque, modele, annee, garage_id) values (55, 'Chevrolet', 'Monte Carlo', 1998, 81);
insert into voitures (id, marque, modele, annee, garage_id) values (56, 'Pontiac', 'Bonneville', 1997, 263);
insert into voitures (id, marque, modele, annee, garage_id) values (57, 'Ford', 'Probe', 1997, 294);
insert into voitures (id, marque, modele, annee, garage_id) values (58, 'Pontiac', 'LeMans', 1990, 218);
insert into voitures (id, marque, modele, annee, garage_id) values (59, 'Suzuki', 'SJ', 1991, 17);
insert into voitures (id, marque, modele, annee, garage_id) values (60, 'Buick', 'Electra', 1987, 46);
insert into voitures (id, marque, modele, annee, garage_id) values (61, 'Ford', 'Five Hundred', 2007, 181);
insert into voitures (id, marque, modele, annee, garage_id) values (62, 'Suzuki', 'Samurai', 1995, 289);
insert into voitures (id, marque, modele, annee, garage_id) values (63, 'Suzuki', 'XL-7', 2004, 116);
insert into voitures (id, marque, modele, annee, garage_id) values (64, 'Ford', 'F150', 1999, 114);
insert into voitures (id, marque, modele, annee, garage_id) values (65, 'Dodge', 'Dakota Club', 1998, 28);
insert into voitures (id, marque, modele, annee, garage_id) values (66, 'Nissan', 'Maxima', 1999, 238);
insert into voitures (id, marque, modele, annee, garage_id) values (67, 'Ford', 'Tempo', 1986, 91);
insert into voitures (id, marque, modele, annee, garage_id) values (68, 'Volvo', '960', 1996, 135);
insert into voitures (id, marque, modele, annee, garage_id) values (69, 'Lexus', 'ES', 1992, 219);
insert into voitures (id, marque, modele, annee, garage_id) values (70, 'GMC', 'Envoy XL', 2005, 242);
insert into voitures (id, marque, modele, annee, garage_id) values (71, 'Honda', 'Civic', 1991, 180);
insert into voitures (id, marque, modele, annee, garage_id) values (72, 'Honda', 'Passport', 2000, 262);
insert into voitures (id, marque, modele, annee, garage_id) values (73, 'Mazda', 'Mazda6 5-Door', 2006, 271);
insert into voitures (id, marque, modele, annee, garage_id) values (74, 'Audi', 'S4', 1994, 54);
insert into voitures (id, marque, modele, annee, garage_id) values (75, 'Suzuki', 'XL7', 2007, 2);
insert into voitures (id, marque, modele, annee, garage_id) values (76, 'BMW', 'X5', 2007, 82);
insert into voitures (id, marque, modele, annee, garage_id) values (77, 'GMC', 'Suburban 2500', 1997, 44);
insert into voitures (id, marque, modele, annee, garage_id) values (78, 'Nissan', 'Cube', 2012, 179);
insert into voitures (id, marque, modele, annee, garage_id) values (79, 'Mitsubishi', 'Mirage', 1985, 276);
insert into voitures (id, marque, modele, annee, garage_id) values (80, 'Acura', 'RL', 1999, 145);
insert into voitures (id, marque, modele, annee, garage_id) values (81, 'Oldsmobile', 'Bravada', 2002, 280);
insert into voitures (id, marque, modele, annee, garage_id) values (82, 'Chrysler', 'Prowler', 2002, 143);
insert into voitures (id, marque, modele, annee, garage_id) values (83, 'Nissan', 'JUKE', 2011, 107);
insert into voitures (id, marque, modele, annee, garage_id) values (84, 'BMW', '5 Series', 1995, 198);
insert into voitures (id, marque, modele, annee, garage_id) values (85, 'Nissan', 'Pathfinder', 1998, 6);
insert into voitures (id, marque, modele, annee, garage_id) values (86, 'BMW', '760', 2003, 140);
insert into voitures (id, marque, modele, annee, garage_id) values (87, 'Bentley', 'Azure T', 2010, 278);
insert into voitures (id, marque, modele, annee, garage_id) values (88, 'Lincoln', 'Continental', 2001, 132);
insert into voitures (id, marque, modele, annee, garage_id) values (89, 'BMW', 'X5', 2001, 11);
insert into voitures (id, marque, modele, annee, garage_id) values (90, 'Toyota', 'Yaris', 2007, 79);
insert into voitures (id, marque, modele, annee, garage_id) values (91, 'BMW', '5 Series', 2007, 196);
insert into voitures (id, marque, modele, annee, garage_id) values (92, 'Rolls-Royce', 'Phantom', 2007, 135);
insert into voitures (id, marque, modele, annee, garage_id) values (93, 'Chevrolet', 'Caprice Classic', 1994, 222);
insert into voitures (id, marque, modele, annee, garage_id) values (94, 'Toyota', 'Celica', 1993, 230);
insert into voitures (id, marque, modele, annee, garage_id) values (95, 'Pontiac', 'Grand Prix', 2004, 191);
insert into voitures (id, marque, modele, annee, garage_id) values (96, 'Chevrolet', 'Corvette', 2006, 13);
insert into voitures (id, marque, modele, annee, garage_id) values (97, 'Pontiac', 'Firebird', 1996, 197);
insert into voitures (id, marque, modele, annee, garage_id) values (98, 'Audi', 'S4', 1993, 143);
insert into voitures (id, marque, modele, annee, garage_id) values (99, 'Acura', 'Integra', 1999, 118);
insert into voitures (id, marque, modele, annee, garage_id) values (100, 'Ford', 'F250', 2011, 290);
insert into voitures (id, marque, modele, annee, garage_id) values (101, 'BMW', '5 Series', 2011, 220);
insert into voitures (id, marque, modele, annee, garage_id) values (102, 'Acura', 'Legend', 1992, 288);
insert into voitures (id, marque, modele, annee, garage_id) values (103, 'Hyundai', 'Accent', 1999, 50);
insert into voitures (id, marque, modele, annee, garage_id) values (104, 'GMC', 'Savana 3500', 1999, 254);
insert into voitures (id, marque, modele, annee, garage_id) values (105, 'MINI', 'Cooper', 2006, 109);
insert into voitures (id, marque, modele, annee, garage_id) values (106, 'Mitsubishi', 'Pajero', 1993, 233);
insert into voitures (id, marque, modele, annee, garage_id) values (107, 'Nissan', 'Frontier', 2009, 240);
insert into voitures (id, marque, modele, annee, garage_id) values (108, 'Ford', 'Econoline E250', 2001, 146);
insert into voitures (id, marque, modele, annee, garage_id) values (109, 'Land Rover', 'Discovery Series II', 2001, 258);
insert into voitures (id, marque, modele, annee, garage_id) values (110, 'Ford', 'Torino', 1970, 241);
insert into voitures (id, marque, modele, annee, garage_id) values (111, 'Ford', 'F250', 2009, 170);
insert into voitures (id, marque, modele, annee, garage_id) values (112, 'Porsche', '911', 1999, 290);
insert into voitures (id, marque, modele, annee, garage_id) values (113, 'Nissan', '280ZX', 1979, 51);
insert into voitures (id, marque, modele, annee, garage_id) values (114, 'Isuzu', 'Stylus', 1993, 251);
insert into voitures (id, marque, modele, annee, garage_id) values (115, 'Hyundai', 'Scoupe', 1994, 242);
insert into voitures (id, marque, modele, annee, garage_id) values (116, 'Nissan', 'Pathfinder', 2007, 85);
insert into voitures (id, marque, modele, annee, garage_id) values (117, 'Ford', 'E-Series', 1963, 27);
insert into voitures (id, marque, modele, annee, garage_id) values (118, 'Mitsubishi', 'Precis', 1994, 265);
insert into voitures (id, marque, modele, annee, garage_id) values (119, 'Volkswagen', 'Corrado', 1992, 115);
insert into voitures (id, marque, modele, annee, garage_id) values (120, 'Nissan', 'Pathfinder', 1995, 54);
insert into voitures (id, marque, modele, annee, garage_id) values (121, 'Mitsubishi', 'Mighty Max', 1986, 133);
insert into voitures (id, marque, modele, annee, garage_id) values (122, 'Chevrolet', 'Beretta', 1993, 189);
insert into voitures (id, marque, modele, annee, garage_id) values (123, 'Mazda', 'Familia', 1988, 105);
insert into voitures (id, marque, modele, annee, garage_id) values (124, 'Mitsubishi', 'Diamante', 2002, 247);
insert into voitures (id, marque, modele, annee, garage_id) values (125, 'Mazda', 'B-Series', 1995, 154);
insert into voitures (id, marque, modele, annee, garage_id) values (126, 'Ford', 'Explorer', 2006, 79);
insert into voitures (id, marque, modele, annee, garage_id) values (127, 'Infiniti', 'Q', 2001, 1);
insert into voitures (id, marque, modele, annee, garage_id) values (128, 'Mercedes-Benz', 'SL-Class', 1990, 26);
insert into voitures (id, marque, modele, annee, garage_id) values (129, 'Dodge', 'Ram 1500', 2006, 134);
insert into voitures (id, marque, modele, annee, garage_id) values (130, 'Land Rover', 'Defender 90', 1995, 120);
insert into voitures (id, marque, modele, annee, garage_id) values (131, 'Audi', '100', 1994, 51);
insert into voitures (id, marque, modele, annee, garage_id) values (132, 'Honda', 'CR-V', 2009, 294);
insert into voitures (id, marque, modele, annee, garage_id) values (133, 'Dodge', 'Grand Caravan', 2001, 289);
insert into voitures (id, marque, modele, annee, garage_id) values (134, 'Kia', 'Sorento', 2004, 297);
insert into voitures (id, marque, modele, annee, garage_id) values (135, 'Lotus', 'Esprit', 1986, 223);
insert into voitures (id, marque, modele, annee, garage_id) values (136, 'Suzuki', 'XL-7', 2001, 244);
insert into voitures (id, marque, modele, annee, garage_id) values (137, 'Dodge', 'Ram 3500', 2005, 126);
insert into voitures (id, marque, modele, annee, garage_id) values (138, 'Pontiac', 'GTO', 1970, 81);
insert into voitures (id, marque, modele, annee, garage_id) values (139, 'BMW', 'M3', 2010, 63);
insert into voitures (id, marque, modele, annee, garage_id) values (140, 'Dodge', 'Caliber', 2011, 81);
insert into voitures (id, marque, modele, annee, garage_id) values (141, 'Mercury', 'Tracer', 1999, 61);
insert into voitures (id, marque, modele, annee, garage_id) values (142, 'Toyota', 'RAV4', 1999, 115);
insert into voitures (id, marque, modele, annee, garage_id) values (143, 'Mitsubishi', 'Mirage', 1986, 250);
insert into voitures (id, marque, modele, annee, garage_id) values (144, 'Land Rover', 'Defender Ice Edition', 2010, 107);
insert into voitures (id, marque, modele, annee, garage_id) values (145, 'GMC', 'Canyon', 2010, 239);
insert into voitures (id, marque, modele, annee, garage_id) values (146, 'Isuzu', 'Trooper', 1994, 27);
insert into voitures (id, marque, modele, annee, garage_id) values (147, 'Oldsmobile', 'Bravada', 2001, 245);
insert into voitures (id, marque, modele, annee, garage_id) values (148, 'Dodge', 'Grand Caravan', 1995, 109);
insert into voitures (id, marque, modele, annee, garage_id) values (149, 'Oldsmobile', 'Cutlass Supreme', 1995, 190);
insert into voitures (id, marque, modele, annee, garage_id) values (150, 'GMC', 'Savana 2500', 2010, 242);
insert into voitures (id, marque, modele, annee, garage_id) values (151, 'Honda', 'CR-X', 1985, 99);
insert into voitures (id, marque, modele, annee, garage_id) values (152, 'Nissan', 'Titan', 2005, 198);
insert into voitures (id, marque, modele, annee, garage_id) values (153, 'Honda', 'Ridgeline', 2008, 32);
insert into voitures (id, marque, modele, annee, garage_id) values (154, 'Oldsmobile', 'Cutlass Supreme', 1997, 283);
insert into voitures (id, marque, modele, annee, garage_id) values (155, 'Volkswagen', 'Cabriolet', 2000, 226);
insert into voitures (id, marque, modele, annee, garage_id) values (156, 'Buick', 'LaCrosse', 2005, 181);
insert into voitures (id, marque, modele, annee, garage_id) values (157, 'Dodge', 'Magnum', 2006, 20);
insert into voitures (id, marque, modele, annee, garage_id) values (158, 'Chevrolet', 'Cobalt', 2009, 142);
insert into voitures (id, marque, modele, annee, garage_id) values (159, 'Dodge', 'Neon', 2002, 72);
insert into voitures (id, marque, modele, annee, garage_id) values (160, 'Cadillac', 'Escalade ESV', 2003, 240);
insert into voitures (id, marque, modele, annee, garage_id) values (161, 'Ford', 'Thunderbird', 1977, 174);
insert into voitures (id, marque, modele, annee, garage_id) values (162, 'Mitsubishi', 'Chariot', 1985, 187);
insert into voitures (id, marque, modele, annee, garage_id) values (163, 'Oldsmobile', 'Bravada', 2004, 134);
insert into voitures (id, marque, modele, annee, garage_id) values (164, 'BMW', '3 Series', 1994, 156);
insert into voitures (id, marque, modele, annee, garage_id) values (165, 'Volkswagen', 'Eos', 2007, 73);
insert into voitures (id, marque, modele, annee, garage_id) values (166, 'Toyota', 'Avalon', 1996, 13);
insert into voitures (id, marque, modele, annee, garage_id) values (167, 'GMC', 'Sonoma', 1998, 74);
insert into voitures (id, marque, modele, annee, garage_id) values (168, 'Ford', 'Th!nk', 2000, 250);
insert into voitures (id, marque, modele, annee, garage_id) values (169, 'Mercedes-Benz', 'SL-Class', 2001, 220);
insert into voitures (id, marque, modele, annee, garage_id) values (170, 'Pontiac', 'Bonneville', 1992, 44);
insert into voitures (id, marque, modele, annee, garage_id) values (171, 'Volkswagen', 'Eos', 2010, 275);
insert into voitures (id, marque, modele, annee, garage_id) values (172, 'Toyota', 'Camry', 2008, 154);
insert into voitures (id, marque, modele, annee, garage_id) values (173, 'BMW', 'Z8', 2000, 107);
insert into voitures (id, marque, modele, annee, garage_id) values (174, 'Volkswagen', 'Passat', 2010, 177);
insert into voitures (id, marque, modele, annee, garage_id) values (175, 'Volvo', '240', 1992, 162);
insert into voitures (id, marque, modele, annee, garage_id) values (176, 'Mercury', 'Grand Marquis', 1993, 72);
insert into voitures (id, marque, modele, annee, garage_id) values (177, 'Ford', 'Taurus', 1986, 71);
insert into voitures (id, marque, modele, annee, garage_id) values (178, 'Ford', 'Windstar', 2004, 154);
insert into voitures (id, marque, modele, annee, garage_id) values (179, 'Audi', 'Q5', 2012, 255);
insert into voitures (id, marque, modele, annee, garage_id) values (180, 'Honda', 'Odyssey', 2006, 249);
insert into voitures (id, marque, modele, annee, garage_id) values (181, 'Chevrolet', 'Tahoe', 2004, 257);
insert into voitures (id, marque, modele, annee, garage_id) values (182, 'Kia', 'Spectra5', 2006, 190);
insert into voitures (id, marque, modele, annee, garage_id) values (183, 'Chevrolet', 'Equinox', 2006, 208);
insert into voitures (id, marque, modele, annee, garage_id) values (184, 'GMC', '1500 Club Coupe', 1998, 103);
insert into voitures (id, marque, modele, annee, garage_id) values (185, 'GMC', 'Sierra 1500', 2004, 129);
insert into voitures (id, marque, modele, annee, garage_id) values (186, 'Mazda', 'MX-6', 1997, 111);
insert into voitures (id, marque, modele, annee, garage_id) values (187, 'Kia', 'Spectra', 2002, 116);
insert into voitures (id, marque, modele, annee, garage_id) values (188, 'Toyota', 'T100 Xtra', 1995, 134);
insert into voitures (id, marque, modele, annee, garage_id) values (189, 'Audi', 'R8', 2011, 66);
insert into voitures (id, marque, modele, annee, garage_id) values (190, 'Chevrolet', 'G-Series 1500', 1997, 76);
insert into voitures (id, marque, modele, annee, garage_id) values (191, 'Volvo', '850', 1997, 140);
insert into voitures (id, marque, modele, annee, garage_id) values (192, 'Porsche', 'Cayman', 2006, 272);
insert into voitures (id, marque, modele, annee, garage_id) values (193, 'Toyota', 'Solara', 1999, 131);
insert into voitures (id, marque, modele, annee, garage_id) values (194, 'Subaru', 'Justy', 1993, 213);
insert into voitures (id, marque, modele, annee, garage_id) values (195, 'Land Rover', 'Discovery Series II', 2001, 136);
insert into voitures (id, marque, modele, annee, garage_id) values (196, 'Honda', 'Odyssey', 1999, 123);
insert into voitures (id, marque, modele, annee, garage_id) values (197, 'Dodge', 'Intrepid', 2001, 117);
insert into voitures (id, marque, modele, annee, garage_id) values (198, 'Plymouth', 'Sundance', 1993, 138);
insert into voitures (id, marque, modele, annee, garage_id) values (199, 'Audi', 'A3', 2010, 179);
insert into voitures (id, marque, modele, annee, garage_id) values (200, 'Land Rover', 'LR2', 2012, 189);
insert into voitures (id, marque, modele, annee, garage_id) values (201, 'Ford', 'Mustang', 1980, 153);
insert into voitures (id, marque, modele, annee, garage_id) values (202, 'Cadillac', 'XLR-V', 2009, 146);
insert into voitures (id, marque, modele, annee, garage_id) values (203, 'Volkswagen', 'Cabriolet', 2000, 169);
insert into voitures (id, marque, modele, annee, garage_id) values (204, 'Toyota', '4Runner', 2012, 138);
insert into voitures (id, marque, modele, annee, garage_id) values (205, 'Chevrolet', 'G-Series 2500', 1997, 56);
insert into voitures (id, marque, modele, annee, garage_id) values (206, 'Nissan', 'NV3500', 2012, 123);
insert into voitures (id, marque, modele, annee, garage_id) values (207, 'GMC', 'Savana 2500', 2007, 183);
insert into voitures (id, marque, modele, annee, garage_id) values (208, 'Ford', 'Escape', 2002, 90);
insert into voitures (id, marque, modele, annee, garage_id) values (209, 'Nissan', 'Maxima', 2007, 90);
insert into voitures (id, marque, modele, annee, garage_id) values (210, 'Chevrolet', 'Corvette', 1998, 180);
insert into voitures (id, marque, modele, annee, garage_id) values (211, 'Dodge', 'Ram 1500', 2002, 12);
insert into voitures (id, marque, modele, annee, garage_id) values (212, 'Ford', 'Thunderbird', 2005, 52);
insert into voitures (id, marque, modele, annee, garage_id) values (213, 'Volvo', 'C30', 2011, 253);
insert into voitures (id, marque, modele, annee, garage_id) values (214, 'Subaru', 'XT', 1985, 204);
insert into voitures (id, marque, modele, annee, garage_id) values (215, 'Volkswagen', 'Scirocco', 1984, 57);
insert into voitures (id, marque, modele, annee, garage_id) values (216, 'Mercedes-Benz', 'R-Class', 2012, 162);
insert into voitures (id, marque, modele, annee, garage_id) values (217, 'Mercury', 'Villager', 2001, 97);
insert into voitures (id, marque, modele, annee, garage_id) values (218, 'Land Rover', 'LR2', 2012, 79);
insert into voitures (id, marque, modele, annee, garage_id) values (219, 'Mitsubishi', 'Pajero', 1992, 138);
insert into voitures (id, marque, modele, annee, garage_id) values (220, 'Mitsubishi', 'Endeavor', 2009, 57);
insert into voitures (id, marque, modele, annee, garage_id) values (221, 'Nissan', 'Sentra', 2000, 72);
insert into voitures (id, marque, modele, annee, garage_id) values (222, 'GMC', 'Yukon XL 2500', 2008, 105);
insert into voitures (id, marque, modele, annee, garage_id) values (223, 'Chevrolet', 'Lumina', 2000, 80);
insert into voitures (id, marque, modele, annee, garage_id) values (224, 'Nissan', 'Xterra', 2004, 34);
insert into voitures (id, marque, modele, annee, garage_id) values (225, 'Honda', 'Civic', 2012, 281);
insert into voitures (id, marque, modele, annee, garage_id) values (226, 'Nissan', 'Rogue', 2011, 200);
insert into voitures (id, marque, modele, annee, garage_id) values (227, 'Suzuki', 'Samurai', 1993, 247);
insert into voitures (id, marque, modele, annee, garage_id) values (228, 'Ford', 'Escort', 1993, 99);
insert into voitures (id, marque, modele, annee, garage_id) values (229, 'BMW', 'X5', 2009, 78);
insert into voitures (id, marque, modele, annee, garage_id) values (230, 'Jaguar', 'XJ Series', 2001, 60);
insert into voitures (id, marque, modele, annee, garage_id) values (231, 'Isuzu', 'Stylus', 1993, 131);
insert into voitures (id, marque, modele, annee, garage_id) values (232, 'Pontiac', 'Grand Prix', 1981, 35);
insert into voitures (id, marque, modele, annee, garage_id) values (233, 'Pontiac', 'Grand Am', 1996, 168);
insert into voitures (id, marque, modele, annee, garage_id) values (234, 'Pontiac', 'Grand Am', 1993, 30);
insert into voitures (id, marque, modele, annee, garage_id) values (235, 'Pontiac', 'G6', 2010, 273);
insert into voitures (id, marque, modele, annee, garage_id) values (236, 'Acura', 'TL', 1997, 286);
insert into voitures (id, marque, modele, annee, garage_id) values (237, 'BMW', '530', 2002, 114);
insert into voitures (id, marque, modele, annee, garage_id) values (238, 'Chrysler', 'Concorde', 1994, 142);
insert into voitures (id, marque, modele, annee, garage_id) values (239, 'Chevrolet', 'Caprice', 1991, 243);
insert into voitures (id, marque, modele, annee, garage_id) values (240, 'Corbin', 'Sparrow', 1999, 171);
insert into voitures (id, marque, modele, annee, garage_id) values (241, 'Kia', 'Forte', 2012, 28);
insert into voitures (id, marque, modele, annee, garage_id) values (242, 'Kia', 'Rio', 2006, 266);
insert into voitures (id, marque, modele, annee, garage_id) values (243, 'Mercedes-Benz', 'CL-Class', 2012, 174);
insert into voitures (id, marque, modele, annee, garage_id) values (244, 'Subaru', 'Outback Sport', 2002, 17);
insert into voitures (id, marque, modele, annee, garage_id) values (245, 'Dodge', 'Ram 2500', 1995, 108);
insert into voitures (id, marque, modele, annee, garage_id) values (246, 'Volvo', 'C70', 2012, 268);
insert into voitures (id, marque, modele, annee, garage_id) values (247, 'Mitsubishi', '3000GT', 1993, 167);
insert into voitures (id, marque, modele, annee, garage_id) values (248, 'Toyota', 'Celica', 1984, 91);
insert into voitures (id, marque, modele, annee, garage_id) values (249, 'Ford', 'E-350 Super Duty Van', 2006, 260);
insert into voitures (id, marque, modele, annee, garage_id) values (250, 'Volvo', 'XC60', 2010, 290);
insert into voitures (id, marque, modele, annee, garage_id) values (251, 'Dodge', 'Ram Van 2500', 2002, 237);
insert into voitures (id, marque, modele, annee, garage_id) values (252, 'Chrysler', 'PT Cruiser', 2010, 38);
insert into voitures (id, marque, modele, annee, garage_id) values (253, 'Dodge', 'Ram 1500', 2002, 4);
insert into voitures (id, marque, modele, annee, garage_id) values (254, 'GMC', 'Canyon', 2010, 180);
insert into voitures (id, marque, modele, annee, garage_id) values (255, 'GMC', 'Yukon XL 1500', 2013, 275);
insert into voitures (id, marque, modele, annee, garage_id) values (256, 'Mazda', 'Mazdaspeed 3', 2012, 290);
insert into voitures (id, marque, modele, annee, garage_id) values (257, 'Chrysler', 'Town & Country', 2010, 86);
insert into voitures (id, marque, modele, annee, garage_id) values (258, 'Mazda', 'Mazda6', 2005, 47);
insert into voitures (id, marque, modele, annee, garage_id) values (259, 'Scion', 'xB', 2009, 34);
insert into voitures (id, marque, modele, annee, garage_id) values (260, 'Ford', 'Econoline E250', 1992, 256);
insert into voitures (id, marque, modele, annee, garage_id) values (261, 'Buick', 'Riviera', 1989, 278);
insert into voitures (id, marque, modele, annee, garage_id) values (262, 'Porsche', 'Boxster', 2013, 224);
insert into voitures (id, marque, modele, annee, garage_id) values (263, 'Mazda', 'Mazda3', 2005, 265);
insert into voitures (id, marque, modele, annee, garage_id) values (264, 'Acura', 'NSX', 2005, 269);
insert into voitures (id, marque, modele, annee, garage_id) values (265, 'Buick', 'Riviera', 1992, 16);
insert into voitures (id, marque, modele, annee, garage_id) values (266, 'Oldsmobile', 'Silhouette', 2002, 139);
insert into voitures (id, marque, modele, annee, garage_id) values (267, 'GMC', 'Suburban 1500', 1998, 54);
insert into voitures (id, marque, modele, annee, garage_id) values (268, 'Pontiac', 'Torrent', 2007, 227);
insert into voitures (id, marque, modele, annee, garage_id) values (269, 'Mitsubishi', 'Diamante', 1996, 195);
insert into voitures (id, marque, modele, annee, garage_id) values (270, 'Ford', 'EXP', 1986, 300);
insert into voitures (id, marque, modele, annee, garage_id) values (271, 'GMC', 'Yukon', 2006, 171);
insert into voitures (id, marque, modele, annee, garage_id) values (272, 'Porsche', '911', 1998, 278);
insert into voitures (id, marque, modele, annee, garage_id) values (273, 'Mazda', 'MX-5', 2002, 95);
insert into voitures (id, marque, modele, annee, garage_id) values (274, 'Pontiac', 'Firebird Formula', 1992, 124);
insert into voitures (id, marque, modele, annee, garage_id) values (275, 'Mitsubishi', 'Endeavor', 2011, 116);
insert into voitures (id, marque, modele, annee, garage_id) values (276, 'BMW', 'X6 M', 2013, 149);
insert into voitures (id, marque, modele, annee, garage_id) values (277, 'Chrysler', '300', 2008, 211);
insert into voitures (id, marque, modele, annee, garage_id) values (278, 'Ford', 'Flex', 2010, 132);
insert into voitures (id, marque, modele, annee, garage_id) values (279, 'Chevrolet', 'Lumina', 1997, 114);
insert into voitures (id, marque, modele, annee, garage_id) values (280, 'Toyota', 'Camry', 1997, 294);
insert into voitures (id, marque, modele, annee, garage_id) values (281, 'Audi', 'A4', 2006, 29);
insert into voitures (id, marque, modele, annee, garage_id) values (282, 'Infiniti', 'G35', 2006, 44);
insert into voitures (id, marque, modele, annee, garage_id) values (283, 'Pontiac', 'Daewoo Kalos', 2006, 56);
insert into voitures (id, marque, modele, annee, garage_id) values (284, 'Isuzu', 'Rodeo Sport', 2002, 239);
insert into voitures (id, marque, modele, annee, garage_id) values (285, 'Mazda', 'Mazdaspeed 3', 2009, 65);
insert into voitures (id, marque, modele, annee, garage_id) values (286, 'Dodge', 'D150', 1992, 179);
insert into voitures (id, marque, modele, annee, garage_id) values (287, 'Mercedes-Benz', 'E-Class', 1999, 191);
insert into voitures (id, marque, modele, annee, garage_id) values (288, 'BMW', 'Z4 M Roadster', 2009, 143);
insert into voitures (id, marque, modele, annee, garage_id) values (289, 'GMC', 'Yukon XL', 2006, 165);
insert into voitures (id, marque, modele, annee, garage_id) values (290, 'Ford', 'E-Series', 2007, 102);
insert into voitures (id, marque, modele, annee, garage_id) values (291, 'Jaguar', 'XF', 2012, 210);
insert into voitures (id, marque, modele, annee, garage_id) values (292, 'Dodge', 'Durango', 2000, 188);
insert into voitures (id, marque, modele, annee, garage_id) values (293, 'GMC', '1500', 1998, 83);
insert into voitures (id, marque, modele, annee, garage_id) values (294, 'Toyota', '4Runner', 2011, 281);
insert into voitures (id, marque, modele, annee, garage_id) values (295, 'Buick', 'Skylark', 1989, 260);
insert into voitures (id, marque, modele, annee, garage_id) values (296, 'Hummer', 'H1', 1998, 41);
insert into voitures (id, marque, modele, annee, garage_id) values (297, 'Jeep', 'Wrangler', 2005, 24);
insert into voitures (id, marque, modele, annee, garage_id) values (298, 'Mercury', 'Grand Marquis', 1990, 166);
insert into voitures (id, marque, modele, annee, garage_id) values (299, 'Lincoln', 'Town Car', 1991, 13);
insert into voitures (id, marque, modele, annee, garage_id) values (300, 'Chevrolet', 'Express 2500', 2008, 66);
insert into voitures (id, marque, modele, annee, garage_id) values (301, 'Jeep', 'Grand Cherokee', 2002, 297);
insert into voitures (id, marque, modele, annee, garage_id) values (302, 'Pontiac', 'Firebird', 1992, 21);
insert into voitures (id, marque, modele, annee, garage_id) values (303, 'Mercedes-Benz', 'S-Class', 2008, 86);
insert into voitures (id, marque, modele, annee, garage_id) values (304, 'Volkswagen', 'Jetta', 1996, 134);
insert into voitures (id, marque, modele, annee, garage_id) values (305, 'Ford', 'E-Series', 1985, 215);
insert into voitures (id, marque, modele, annee, garage_id) values (306, 'Pontiac', 'Sunbird', 1991, 128);
insert into voitures (id, marque, modele, annee, garage_id) values (307, 'Volkswagen', 'GTI', 1988, 1);
insert into voitures (id, marque, modele, annee, garage_id) values (308, 'Pontiac', 'Aztek', 2005, 18);
insert into voitures (id, marque, modele, annee, garage_id) values (309, 'Buick', 'Riviera', 1997, 212);
insert into voitures (id, marque, modele, annee, garage_id) values (310, 'Honda', 'Odyssey', 2011, 185);
insert into voitures (id, marque, modele, annee, garage_id) values (311, 'Mercury', 'Topaz', 1985, 257);
insert into voitures (id, marque, modele, annee, garage_id) values (312, 'Honda', 'Accord', 2008, 45);
insert into voitures (id, marque, modele, annee, garage_id) values (313, 'Cadillac', 'Escalade', 2008, 196);
insert into voitures (id, marque, modele, annee, garage_id) values (314, 'Ford', 'Explorer Sport Trac', 2003, 43);
insert into voitures (id, marque, modele, annee, garage_id) values (315, 'Toyota', 'Tundra', 2009, 142);
insert into voitures (id, marque, modele, annee, garage_id) values (316, 'Toyota', '4Runner', 2012, 168);
insert into voitures (id, marque, modele, annee, garage_id) values (317, 'Ford', 'Laser', 1985, 13);
insert into voitures (id, marque, modele, annee, garage_id) values (318, 'Pontiac', 'Grand Prix', 1994, 268);
insert into voitures (id, marque, modele, annee, garage_id) values (319, 'Lamborghini', 'Countach', 1985, 170);
insert into voitures (id, marque, modele, annee, garage_id) values (320, 'Saab', '9-7X', 2009, 81);
insert into voitures (id, marque, modele, annee, garage_id) values (321, 'Mercedes-Benz', 'E-Class', 2007, 225);
insert into voitures (id, marque, modele, annee, garage_id) values (322, 'Land Rover', 'Discovery Series II', 2001, 293);
insert into voitures (id, marque, modele, annee, garage_id) values (323, 'Isuzu', 'Rodeo', 2004, 255);
insert into voitures (id, marque, modele, annee, garage_id) values (324, 'Kia', 'Spectra', 2007, 59);
insert into voitures (id, marque, modele, annee, garage_id) values (325, 'BMW', '7 Series', 2012, 35);
insert into voitures (id, marque, modele, annee, garage_id) values (326, 'Chevrolet', 'Suburban 1500', 2006, 177);
insert into voitures (id, marque, modele, annee, garage_id) values (327, 'GMC', 'Yukon XL 1500', 2013, 18);
insert into voitures (id, marque, modele, annee, garage_id) values (328, 'Jeep', 'Patriot', 2011, 58);
insert into voitures (id, marque, modele, annee, garage_id) values (329, 'Volkswagen', 'Touareg 2', 2009, 271);
insert into voitures (id, marque, modele, annee, garage_id) values (330, 'Mazda', 'B-Series', 2005, 78);
insert into voitures (id, marque, modele, annee, garage_id) values (331, 'Buick', 'Coachbuilder', 1992, 103);
insert into voitures (id, marque, modele, annee, garage_id) values (332, 'Chrysler', 'PT Cruiser', 2001, 268);
insert into voitures (id, marque, modele, annee, garage_id) values (333, 'Pontiac', 'Grand Prix', 1979, 293);
insert into voitures (id, marque, modele, annee, garage_id) values (334, 'BMW', 'Z4 M', 2007, 295);
insert into voitures (id, marque, modele, annee, garage_id) values (335, 'Honda', 'Odyssey', 1997, 147);
insert into voitures (id, marque, modele, annee, garage_id) values (336, 'Toyota', 'Previa', 1993, 117);
insert into voitures (id, marque, modele, annee, garage_id) values (337, 'Chrysler', 'PT Cruiser', 2007, 5);
insert into voitures (id, marque, modele, annee, garage_id) values (338, 'BMW', 'M', 2000, 140);
insert into voitures (id, marque, modele, annee, garage_id) values (339, 'Dodge', 'Ram Van B150', 1994, 111);
insert into voitures (id, marque, modele, annee, garage_id) values (340, 'Kia', 'Amanti', 2006, 235);
insert into voitures (id, marque, modele, annee, garage_id) values (341, 'GMC', 'Canyon', 2006, 44);
insert into voitures (id, marque, modele, annee, garage_id) values (342, 'Mercedes-Benz', '600SEL', 1993, 254);
insert into voitures (id, marque, modele, annee, garage_id) values (343, 'Nissan', 'Maxima', 1998, 39);
insert into voitures (id, marque, modele, annee, garage_id) values (344, 'Subaru', 'Impreza', 2012, 238);
insert into voitures (id, marque, modele, annee, garage_id) values (345, 'BMW', 'X6 M', 2010, 50);
insert into voitures (id, marque, modele, annee, garage_id) values (346, 'GMC', 'Yukon', 2000, 243);
insert into voitures (id, marque, modele, annee, garage_id) values (347, 'Infiniti', 'G37', 2012, 278);
insert into voitures (id, marque, modele, annee, garage_id) values (348, 'Nissan', '200SX', 1997, 286);
insert into voitures (id, marque, modele, annee, garage_id) values (349, 'Ford', 'Expedition', 2007, 65);
insert into voitures (id, marque, modele, annee, garage_id) values (350, 'Kia', 'Optima', 2003, 47);
insert into voitures (id, marque, modele, annee, garage_id) values (351, 'Mitsubishi', 'Endeavor', 2008, 42);
insert into voitures (id, marque, modele, annee, garage_id) values (352, 'Buick', 'LeSabre', 2001, 146);
insert into voitures (id, marque, modele, annee, garage_id) values (353, 'Oldsmobile', 'Silhouette', 2003, 297);
insert into voitures (id, marque, modele, annee, garage_id) values (354, 'Audi', 'A8', 2011, 29);
insert into voitures (id, marque, modele, annee, garage_id) values (355, 'Hyundai', 'Sonata', 2002, 204);
insert into voitures (id, marque, modele, annee, garage_id) values (356, 'Kia', 'Spectra', 2003, 51);
insert into voitures (id, marque, modele, annee, garage_id) values (357, 'Chevrolet', 'Silverado', 1999, 112);
insert into voitures (id, marque, modele, annee, garage_id) values (358, 'Aston Martin', 'DB9', 2011, 89);
insert into voitures (id, marque, modele, annee, garage_id) values (359, 'Mazda', '626', 1991, 186);
insert into voitures (id, marque, modele, annee, garage_id) values (360, 'Volvo', 'V70', 2005, 46);
insert into voitures (id, marque, modele, annee, garage_id) values (361, 'Isuzu', 'i-Series', 2007, 52);
insert into voitures (id, marque, modele, annee, garage_id) values (362, 'Suzuki', 'Forenza', 2004, 114);
insert into voitures (id, marque, modele, annee, garage_id) values (363, 'Smart', 'Fortwo', 2010, 59);
insert into voitures (id, marque, modele, annee, garage_id) values (364, 'Kia', 'Sorento', 2007, 187);
insert into voitures (id, marque, modele, annee, garage_id) values (365, 'Dodge', 'Grand Caravan', 1993, 205);
insert into voitures (id, marque, modele, annee, garage_id) values (366, 'Toyota', 'Echo', 2001, 159);
insert into voitures (id, marque, modele, annee, garage_id) values (367, 'Lamborghini', 'Countach', 1985, 32);
insert into voitures (id, marque, modele, annee, garage_id) values (368, 'GMC', 'Envoy XUV', 2005, 216);
insert into voitures (id, marque, modele, annee, garage_id) values (369, 'Bentley', 'Continental GT', 2010, 47);
insert into voitures (id, marque, modele, annee, garage_id) values (370, 'Honda', 'Civic', 1995, 3);
insert into voitures (id, marque, modele, annee, garage_id) values (371, 'Ford', 'Focus', 2005, 252);
insert into voitures (id, marque, modele, annee, garage_id) values (372, 'Chevrolet', 'Suburban 1500', 1994, 152);
insert into voitures (id, marque, modele, annee, garage_id) values (373, 'Dodge', 'Ramcharger', 1993, 212);
insert into voitures (id, marque, modele, annee, garage_id) values (374, 'Lexus', 'RX Hybrid', 2006, 56);
insert into voitures (id, marque, modele, annee, garage_id) values (375, 'Maserati', 'Quattroporte', 1984, 176);
insert into voitures (id, marque, modele, annee, garage_id) values (376, 'Ford', 'Country', 1967, 218);
insert into voitures (id, marque, modele, annee, garage_id) values (377, 'GMC', 'Sonoma', 2001, 224);
insert into voitures (id, marque, modele, annee, garage_id) values (378, 'Cadillac', 'XLR', 2006, 36);
insert into voitures (id, marque, modele, annee, garage_id) values (379, 'Toyota', 'Xtra', 1992, 227);
insert into voitures (id, marque, modele, annee, garage_id) values (380, 'Ford', 'Bronco II', 1989, 109);
insert into voitures (id, marque, modele, annee, garage_id) values (381, 'Lincoln', 'Continental Mark VII', 1990, 215);
insert into voitures (id, marque, modele, annee, garage_id) values (382, 'Cadillac', 'DeVille', 1997, 182);
insert into voitures (id, marque, modele, annee, garage_id) values (383, 'Chevrolet', 'Corvette', 1986, 265);
insert into voitures (id, marque, modele, annee, garage_id) values (384, 'Suzuki', 'Aerio', 2007, 258);
insert into voitures (id, marque, modele, annee, garage_id) values (385, 'Pontiac', 'Firebird Trans Am', 1986, 28);
insert into voitures (id, marque, modele, annee, garage_id) values (386, 'Pontiac', 'Grand Prix', 1967, 125);
insert into voitures (id, marque, modele, annee, garage_id) values (387, 'Mitsubishi', '3000GT', 1997, 147);
insert into voitures (id, marque, modele, annee, garage_id) values (388, 'Mitsubishi', 'Montero', 1999, 110);
insert into voitures (id, marque, modele, annee, garage_id) values (389, 'Mazda', 'Miata MX-5', 2005, 224);
insert into voitures (id, marque, modele, annee, garage_id) values (390, 'Dodge', 'Nitro', 2007, 49);
insert into voitures (id, marque, modele, annee, garage_id) values (391, 'Cadillac', 'DeVille', 1995, 161);
insert into voitures (id, marque, modele, annee, garage_id) values (392, 'Chevrolet', 'Uplander', 2007, 290);
insert into voitures (id, marque, modele, annee, garage_id) values (393, 'Chevrolet', 'Silverado 2500', 2006, 134);
insert into voitures (id, marque, modele, annee, garage_id) values (394, 'Lincoln', 'Town Car', 1999, 191);
insert into voitures (id, marque, modele, annee, garage_id) values (395, 'Honda', 'Civic', 1999, 269);
insert into voitures (id, marque, modele, annee, garage_id) values (396, 'Mitsubishi', 'Galant', 1997, 251);
insert into voitures (id, marque, modele, annee, garage_id) values (397, 'Ford', 'E350', 2003, 142);
insert into voitures (id, marque, modele, annee, garage_id) values (398, 'Saab', '9-7X', 2009, 26);
insert into voitures (id, marque, modele, annee, garage_id) values (399, 'GMC', 'Yukon', 2007, 204);
insert into voitures (id, marque, modele, annee, garage_id) values (400, 'Ford', 'Tempo', 1994, 144);
insert into voitures (id, marque, modele, annee, garage_id) values (401, 'Rolls-Royce', 'Phantom', 2008, 178);
insert into voitures (id, marque, modele, annee, garage_id) values (402, 'Ford', 'E350', 2010, 210);
insert into voitures (id, marque, modele, annee, garage_id) values (403, 'Honda', 'Accord', 2008, 137);
insert into voitures (id, marque, modele, annee, garage_id) values (404, 'Subaru', 'Impreza', 1997, 115);
insert into voitures (id, marque, modele, annee, garage_id) values (405, 'Ford', 'E-350 Super Duty', 2006, 71);
insert into voitures (id, marque, modele, annee, garage_id) values (406, 'Chevrolet', 'Tahoe', 2007, 196);
insert into voitures (id, marque, modele, annee, garage_id) values (407, 'Jeep', 'Liberty', 2011, 156);
insert into voitures (id, marque, modele, annee, garage_id) values (408, 'Pontiac', 'Grand Prix', 1986, 151);
insert into voitures (id, marque, modele, annee, garage_id) values (409, 'Honda', 'Insight', 2011, 86);
insert into voitures (id, marque, modele, annee, garage_id) values (410, 'Subaru', 'Impreza', 2000, 11);
insert into voitures (id, marque, modele, annee, garage_id) values (411, 'Chevrolet', 'Impala', 2012, 182);
insert into voitures (id, marque, modele, annee, garage_id) values (412, 'GMC', 'Rally Wagon 2500', 1992, 273);
insert into voitures (id, marque, modele, annee, garage_id) values (413, 'Ford', 'Ranger', 1991, 240);
insert into voitures (id, marque, modele, annee, garage_id) values (414, 'Ford', 'F150', 2010, 130);
insert into voitures (id, marque, modele, annee, garage_id) values (415, 'Land Rover', 'Range Rover', 1988, 203);
insert into voitures (id, marque, modele, annee, garage_id) values (416, 'Lotus', 'Elise', 2010, 239);
insert into voitures (id, marque, modele, annee, garage_id) values (417, 'Audi', 'A8', 2012, 192);
insert into voitures (id, marque, modele, annee, garage_id) values (418, 'Ford', 'E-Series', 2008, 44);
insert into voitures (id, marque, modele, annee, garage_id) values (419, 'Mercedes-Benz', '300CE', 1993, 188);
insert into voitures (id, marque, modele, annee, garage_id) values (420, 'Pontiac', 'Sunfire', 2005, 153);
insert into voitures (id, marque, modele, annee, garage_id) values (421, 'Mitsubishi', 'Eclipse', 2004, 287);
insert into voitures (id, marque, modele, annee, garage_id) values (422, 'Hyundai', 'Tiburon', 2007, 1);
insert into voitures (id, marque, modele, annee, garage_id) values (423, 'Mitsubishi', 'Mighty Max Macro', 1992, 168);
insert into voitures (id, marque, modele, annee, garage_id) values (424, 'Ford', 'Ranger', 1996, 247);
insert into voitures (id, marque, modele, annee, garage_id) values (425, 'Chevrolet', 'Astro', 1992, 140);
insert into voitures (id, marque, modele, annee, garage_id) values (426, 'BMW', 'Z8', 2000, 211);
insert into voitures (id, marque, modele, annee, garage_id) values (427, 'Toyota', 'Camry Hybrid', 2012, 146);
insert into voitures (id, marque, modele, annee, garage_id) values (428, 'Toyota', '4Runner', 2007, 36);
insert into voitures (id, marque, modele, annee, garage_id) values (429, 'Lexus', 'SC', 1992, 84);
insert into voitures (id, marque, modele, annee, garage_id) values (430, 'Mazda', 'MX-5', 1999, 186);
insert into voitures (id, marque, modele, annee, garage_id) values (431, 'Land Rover', 'LR2', 2008, 68);
insert into voitures (id, marque, modele, annee, garage_id) values (432, 'Toyota', 'Land Cruiser', 2010, 244);
insert into voitures (id, marque, modele, annee, garage_id) values (433, 'Mercedes-Benz', 'SL-Class', 2008, 85);
insert into voitures (id, marque, modele, annee, garage_id) values (434, 'Ford', 'Escape', 2007, 47);
insert into voitures (id, marque, modele, annee, garage_id) values (435, 'Chevrolet', 'Malibu', 2001, 241);
insert into voitures (id, marque, modele, annee, garage_id) values (436, 'Lexus', 'SC', 1995, 206);
insert into voitures (id, marque, modele, annee, garage_id) values (437, 'Ford', 'E-Series', 2002, 261);
insert into voitures (id, marque, modele, annee, garage_id) values (438, 'Chevrolet', 'Suburban 1500', 1997, 233);
insert into voitures (id, marque, modele, annee, garage_id) values (439, 'Dodge', 'Durango', 2001, 58);
insert into voitures (id, marque, modele, annee, garage_id) values (440, 'Mercedes-Benz', 'CL-Class', 2005, 103);
insert into voitures (id, marque, modele, annee, garage_id) values (441, 'Dodge', 'Dakota', 2004, 27);
insert into voitures (id, marque, modele, annee, garage_id) values (442, 'Nissan', 'Maxima', 2003, 133);
insert into voitures (id, marque, modele, annee, garage_id) values (443, 'Mitsubishi', 'Montero', 1996, 215);
insert into voitures (id, marque, modele, annee, garage_id) values (444, 'Isuzu', 'i-370', 2007, 165);
insert into voitures (id, marque, modele, annee, garage_id) values (445, 'BMW', 'M3', 1998, 188);
insert into voitures (id, marque, modele, annee, garage_id) values (446, 'Mitsubishi', 'Truck', 1993, 219);
insert into voitures (id, marque, modele, annee, garage_id) values (447, 'Toyota', 'Cressida', 1992, 232);
insert into voitures (id, marque, modele, annee, garage_id) values (448, 'Mazda', 'Mazda6 5-Door', 2006, 132);
insert into voitures (id, marque, modele, annee, garage_id) values (449, 'Audi', '4000s', 1986, 239);
insert into voitures (id, marque, modele, annee, garage_id) values (450, 'Mitsubishi', 'Pajero', 2000, 288);
insert into voitures (id, marque, modele, annee, garage_id) values (451, 'Chrysler', 'Crossfire', 2006, 18);
insert into voitures (id, marque, modele, annee, garage_id) values (452, 'Jeep', 'Grand Cherokee', 2010, 298);
insert into voitures (id, marque, modele, annee, garage_id) values (453, 'Audi', '90', 1991, 87);
insert into voitures (id, marque, modele, annee, garage_id) values (454, 'Acura', 'TSX', 2008, 133);
insert into voitures (id, marque, modele, annee, garage_id) values (455, 'Mercedes-Benz', 'C-Class', 2006, 16);
insert into voitures (id, marque, modele, annee, garage_id) values (456, 'Oldsmobile', 'Cutlass Supreme', 1997, 42);
insert into voitures (id, marque, modele, annee, garage_id) values (457, 'Mazda', 'RX-7', 1988, 194);
insert into voitures (id, marque, modele, annee, garage_id) values (458, 'Kia', 'Sportage', 1995, 54);
insert into voitures (id, marque, modele, annee, garage_id) values (459, 'Bentley', 'Continental GT', 2007, 165);
insert into voitures (id, marque, modele, annee, garage_id) values (460, 'Ford', 'Econoline E150', 1992, 52);
insert into voitures (id, marque, modele, annee, garage_id) values (461, 'Lincoln', 'LS', 2005, 201);
insert into voitures (id, marque, modele, annee, garage_id) values (462, 'Chevrolet', 'Cavalier', 2002, 112);
insert into voitures (id, marque, modele, annee, garage_id) values (463, 'Lincoln', 'Town Car', 2002, 171);
insert into voitures (id, marque, modele, annee, garage_id) values (464, 'GMC', 'Suburban 1500', 1997, 276);
insert into voitures (id, marque, modele, annee, garage_id) values (465, 'Chevrolet', 'Lumina', 1999, 211);
insert into voitures (id, marque, modele, annee, garage_id) values (466, 'Porsche', 'Cayenne', 2005, 190);
insert into voitures (id, marque, modele, annee, garage_id) values (467, 'Scion', 'xD', 2011, 41);
insert into voitures (id, marque, modele, annee, garage_id) values (468, 'Mazda', 'B-Series', 2001, 235);
insert into voitures (id, marque, modele, annee, garage_id) values (469, 'Mercedes-Benz', 'SL-Class', 1992, 144);
insert into voitures (id, marque, modele, annee, garage_id) values (470, 'Mitsubishi', 'Montero Sport', 2002, 100);
insert into voitures (id, marque, modele, annee, garage_id) values (471, 'Ford', 'Explorer Sport Trac', 2001, 277);
insert into voitures (id, marque, modele, annee, garage_id) values (472, 'Volvo', '850', 1995, 278);
insert into voitures (id, marque, modele, annee, garage_id) values (473, 'Toyota', 'T100 Xtra', 1997, 170);
insert into voitures (id, marque, modele, annee, garage_id) values (474, 'Subaru', 'Forester', 1999, 97);
insert into voitures (id, marque, modele, annee, garage_id) values (475, 'Subaru', 'Justy', 1994, 30);
insert into voitures (id, marque, modele, annee, garage_id) values (476, 'GMC', 'Acadia', 2010, 69);
insert into voitures (id, marque, modele, annee, garage_id) values (477, 'Mercury', 'Sable', 2004, 228);
insert into voitures (id, marque, modele, annee, garage_id) values (478, 'Ford', 'Focus', 2004, 87);
insert into voitures (id, marque, modele, annee, garage_id) values (479, 'Tesla', 'Roadster', 2012, 160);
insert into voitures (id, marque, modele, annee, garage_id) values (480, 'Land Rover', 'Defender', 1993, 155);
insert into voitures (id, marque, modele, annee, garage_id) values (481, 'BMW', 'X5 M', 2011, 111);
insert into voitures (id, marque, modele, annee, garage_id) values (482, 'GMC', 'Suburban 1500', 1992, 119);
insert into voitures (id, marque, modele, annee, garage_id) values (483, 'Buick', 'LeSabre', 1999, 36);
insert into voitures (id, marque, modele, annee, garage_id) values (484, 'Maserati', 'Gran Sport', 2006, 31);
insert into voitures (id, marque, modele, annee, garage_id) values (485, 'Infiniti', 'M', 2004, 288);
insert into voitures (id, marque, modele, annee, garage_id) values (486, 'Audi', 'A3', 2007, 60);
insert into voitures (id, marque, modele, annee, garage_id) values (487, 'Lexus', 'LS Hybrid', 2012, 151);
insert into voitures (id, marque, modele, annee, garage_id) values (488, 'Ford', 'Th!nk', 2001, 19);
insert into voitures (id, marque, modele, annee, garage_id) values (489, 'Porsche', '928', 1995, 145);
insert into voitures (id, marque, modele, annee, garage_id) values (490, 'Dodge', 'Ram Van B350', 1992, 60);
insert into voitures (id, marque, modele, annee, garage_id) values (491, 'Scion', 'xD', 2009, 271);
insert into voitures (id, marque, modele, annee, garage_id) values (492, 'Suzuki', 'Grand Vitara', 2009, 252);
insert into voitures (id, marque, modele, annee, garage_id) values (493, 'Pontiac', 'Bonneville', 1989, 90);
insert into voitures (id, marque, modele, annee, garage_id) values (494, 'Mitsubishi', 'Montero Sport', 1997, 41);
insert into voitures (id, marque, modele, annee, garage_id) values (495, 'Mitsubishi', 'Tredia', 1988, 208);
insert into voitures (id, marque, modele, annee, garage_id) values (496, 'Infiniti', 'G', 2010, 153);
insert into voitures (id, marque, modele, annee, garage_id) values (497, 'Saab', '9-7X', 2005, 16);
insert into voitures (id, marque, modele, annee, garage_id) values (498, 'Ford', 'Expedition', 2000, 87);
insert into voitures (id, marque, modele, annee, garage_id) values (499, 'Chevrolet', 'Blazer', 1992, 55);
insert into voitures (id, marque, modele, annee, garage_id) values (500, 'Subaru', 'Baja', 2005, 90);
insert into voitures (id, marque, modele, annee, garage_id) values (501, 'Pontiac', 'LeMans', 1965, 146);
insert into voitures (id, marque, modele, annee, garage_id) values (502, 'Nissan', 'Cube', 2010, 90);
insert into voitures (id, marque, modele, annee, garage_id) values (503, 'Honda', 'Accord', 2001, 60);
insert into voitures (id, marque, modele, annee, garage_id) values (504, 'Volkswagen', 'Golf', 1992, 170);
insert into voitures (id, marque, modele, annee, garage_id) values (505, 'Pontiac', 'Grand Am', 1986, 178);
insert into voitures (id, marque, modele, annee, garage_id) values (506, 'Bentley', 'Brooklands', 2009, 51);
insert into voitures (id, marque, modele, annee, garage_id) values (507, 'BMW', '7 Series', 2005, 109);
insert into voitures (id, marque, modele, annee, garage_id) values (508, 'Dodge', 'Ram 2500', 2004, 262);
insert into voitures (id, marque, modele, annee, garage_id) values (509, 'GMC', 'Rally Wagon G3500', 1995, 282);
insert into voitures (id, marque, modele, annee, garage_id) values (510, 'Mercedes-Benz', 'SLK-Class', 1999, 186);
insert into voitures (id, marque, modele, annee, garage_id) values (511, 'Lamborghini', 'Countach', 1989, 72);
insert into voitures (id, marque, modele, annee, garage_id) values (512, 'Mitsubishi', 'Galant', 2006, 37);
insert into voitures (id, marque, modele, annee, garage_id) values (513, 'Jeep', 'Compass', 2010, 128);
insert into voitures (id, marque, modele, annee, garage_id) values (514, 'Toyota', 'Paseo', 1996, 8);
insert into voitures (id, marque, modele, annee, garage_id) values (515, 'Toyota', 'Highlander', 2001, 146);
insert into voitures (id, marque, modele, annee, garage_id) values (516, 'Mercedes-Benz', 'GLK-Class', 2012, 78);
insert into voitures (id, marque, modele, annee, garage_id) values (517, 'Dodge', 'Viper', 1995, 169);
insert into voitures (id, marque, modele, annee, garage_id) values (518, 'Acura', 'TL', 2002, 201);
insert into voitures (id, marque, modele, annee, garage_id) values (519, 'Volvo', 'V50', 2011, 224);
insert into voitures (id, marque, modele, annee, garage_id) values (520, 'MINI', 'Cooper', 2005, 221);
insert into voitures (id, marque, modele, annee, garage_id) values (521, 'Buick', 'Verano', 2012, 100);
insert into voitures (id, marque, modele, annee, garage_id) values (522, 'Bentley', 'Brooklands', 2009, 238);
insert into voitures (id, marque, modele, annee, garage_id) values (523, 'Ford', 'Escort', 2004, 48);
insert into voitures (id, marque, modele, annee, garage_id) values (524, 'Pontiac', 'Montana', 2001, 53);
insert into voitures (id, marque, modele, annee, garage_id) values (525, 'Ford', 'Mustang', 1986, 222);
insert into voitures (id, marque, modele, annee, garage_id) values (526, 'Dodge', 'Ram 3500', 2006, 192);
insert into voitures (id, marque, modele, annee, garage_id) values (527, 'Chrysler', 'Sebring', 2008, 88);
insert into voitures (id, marque, modele, annee, garage_id) values (528, 'BMW', '3 Series', 1999, 240);
insert into voitures (id, marque, modele, annee, garage_id) values (529, 'Ford', 'Fairlane', 1967, 143);
insert into voitures (id, marque, modele, annee, garage_id) values (530, 'Ford', 'LTD', 1984, 164);
insert into voitures (id, marque, modele, annee, garage_id) values (531, 'Acura', 'TL', 1995, 98);
insert into voitures (id, marque, modele, annee, garage_id) values (532, 'Ford', 'Probe', 1994, 174);
insert into voitures (id, marque, modele, annee, garage_id) values (533, 'Nissan', 'Pathfinder', 2005, 10);
insert into voitures (id, marque, modele, annee, garage_id) values (534, 'Volvo', 'V40', 2000, 14);
insert into voitures (id, marque, modele, annee, garage_id) values (535, 'Mitsubishi', 'Mirage', 1989, 211);
insert into voitures (id, marque, modele, annee, garage_id) values (536, 'Ford', 'F450', 2010, 288);
insert into voitures (id, marque, modele, annee, garage_id) values (537, 'Chevrolet', 'Impala', 1995, 96);
insert into voitures (id, marque, modele, annee, garage_id) values (538, 'Tesla', 'Model S', 2012, 169);
insert into voitures (id, marque, modele, annee, garage_id) values (539, 'Volkswagen', 'Golf', 1991, 253);
insert into voitures (id, marque, modele, annee, garage_id) values (540, 'Mitsubishi', 'Galant', 1990, 208);
insert into voitures (id, marque, modele, annee, garage_id) values (541, 'Audi', 'S6', 2002, 184);
insert into voitures (id, marque, modele, annee, garage_id) values (542, 'Hummer', 'H2', 2007, 228);
insert into voitures (id, marque, modele, annee, garage_id) values (543, 'Volkswagen', 'Touareg 2', 2008, 200);
insert into voitures (id, marque, modele, annee, garage_id) values (544, 'Chevrolet', 'Suburban 2500', 2004, 205);
insert into voitures (id, marque, modele, annee, garage_id) values (545, 'BMW', 'M3', 1996, 169);
insert into voitures (id, marque, modele, annee, garage_id) values (546, 'Cadillac', 'XLR', 2008, 138);
insert into voitures (id, marque, modele, annee, garage_id) values (547, 'Ford', 'E-Series', 2010, 108);
insert into voitures (id, marque, modele, annee, garage_id) values (548, 'Mitsubishi', 'Chariot', 1985, 127);
insert into voitures (id, marque, modele, annee, garage_id) values (549, 'Lexus', 'LX', 2010, 91);
insert into voitures (id, marque, modele, annee, garage_id) values (550, 'Subaru', 'Impreza', 2006, 250);
insert into voitures (id, marque, modele, annee, garage_id) values (551, 'Peugeot', '207', 2006, 269);
insert into voitures (id, marque, modele, annee, garage_id) values (552, 'Saturn', 'Relay', 2007, 283);
insert into voitures (id, marque, modele, annee, garage_id) values (553, 'Ford', 'Explorer Sport Trac', 2010, 151);
insert into voitures (id, marque, modele, annee, garage_id) values (554, 'Nissan', 'Datsun/Nissan Z-car', 1990, 30);
insert into voitures (id, marque, modele, annee, garage_id) values (555, 'Toyota', 'Prius', 2009, 74);
insert into voitures (id, marque, modele, annee, garage_id) values (556, 'Rolls-Royce', 'Phantom', 2012, 293);
insert into voitures (id, marque, modele, annee, garage_id) values (557, 'Volvo', 'XC70', 2005, 91);
insert into voitures (id, marque, modele, annee, garage_id) values (558, 'Mercedes-Benz', 'C-Class', 1995, 140);
insert into voitures (id, marque, modele, annee, garage_id) values (559, 'Nissan', 'Sentra', 1991, 183);
insert into voitures (id, marque, modele, annee, garage_id) values (560, 'Porsche', 'Cayman', 2010, 129);
insert into voitures (id, marque, modele, annee, garage_id) values (561, 'Mercedes-Benz', 'SLK-Class', 2006, 107);
insert into voitures (id, marque, modele, annee, garage_id) values (562, 'Eagle', 'Talon', 1994, 42);
insert into voitures (id, marque, modele, annee, garage_id) values (563, 'Pontiac', 'LeMans', 1993, 187);
insert into voitures (id, marque, modele, annee, garage_id) values (564, 'Volkswagen', 'Golf', 1990, 181);
insert into voitures (id, marque, modele, annee, garage_id) values (565, 'Chevrolet', 'Silverado 2500', 2003, 211);
insert into voitures (id, marque, modele, annee, garage_id) values (566, 'Ford', 'Contour', 1999, 265);
insert into voitures (id, marque, modele, annee, garage_id) values (567, 'Smart', 'Fortwo', 2010, 268);
insert into voitures (id, marque, modele, annee, garage_id) values (568, 'Ford', 'F350', 1999, 280);
insert into voitures (id, marque, modele, annee, garage_id) values (569, 'Mitsubishi', 'Outlander', 2008, 272);
insert into voitures (id, marque, modele, annee, garage_id) values (570, 'Mercury', 'Sable', 1994, 42);
insert into voitures (id, marque, modele, annee, garage_id) values (571, 'Lamborghini', 'Murciélago', 2010, 40);
insert into voitures (id, marque, modele, annee, garage_id) values (572, 'BMW', 'Z3', 2000, 170);
insert into voitures (id, marque, modele, annee, garage_id) values (573, 'GMC', 'Envoy', 2006, 46);
insert into voitures (id, marque, modele, annee, garage_id) values (574, 'Mercedes-Benz', 'GLK-Class', 2012, 99);
insert into voitures (id, marque, modele, annee, garage_id) values (575, 'Mercury', 'Cougar', 1991, 96);
insert into voitures (id, marque, modele, annee, garage_id) values (576, 'Dodge', 'Neon', 1995, 124);
insert into voitures (id, marque, modele, annee, garage_id) values (577, 'Dodge', 'Dakota', 2011, 177);
insert into voitures (id, marque, modele, annee, garage_id) values (578, 'Mitsubishi', 'L300', 1990, 136);
insert into voitures (id, marque, modele, annee, garage_id) values (579, 'Hyundai', 'Sonata', 1994, 183);
insert into voitures (id, marque, modele, annee, garage_id) values (580, 'Volkswagen', 'Scirocco', 1986, 72);
insert into voitures (id, marque, modele, annee, garage_id) values (581, 'Dodge', 'Stealth', 1994, 25);
insert into voitures (id, marque, modele, annee, garage_id) values (582, 'Toyota', 'Prius', 2008, 250);
insert into voitures (id, marque, modele, annee, garage_id) values (583, 'Ford', 'E-Series', 2010, 264);
insert into voitures (id, marque, modele, annee, garage_id) values (584, 'Nissan', 'Titan', 2012, 216);
insert into voitures (id, marque, modele, annee, garage_id) values (585, 'Mercedes-Benz', 'SLR McLaren', 2006, 94);
insert into voitures (id, marque, modele, annee, garage_id) values (586, 'Mercedes-Benz', 'CLK-Class', 2004, 166);
insert into voitures (id, marque, modele, annee, garage_id) values (587, 'GMC', 'Sierra 3500', 2000, 195);
insert into voitures (id, marque, modele, annee, garage_id) values (588, 'Lincoln', 'Town Car', 1997, 212);
insert into voitures (id, marque, modele, annee, garage_id) values (589, 'GMC', 'Savana 2500', 2001, 229);
insert into voitures (id, marque, modele, annee, garage_id) values (590, 'Oldsmobile', 'Toronado', 1966, 227);
insert into voitures (id, marque, modele, annee, garage_id) values (591, 'Mitsubishi', 'Mirage', 1987, 203);
insert into voitures (id, marque, modele, annee, garage_id) values (592, 'Cadillac', 'Eldorado', 1994, 183);
insert into voitures (id, marque, modele, annee, garage_id) values (593, 'Plymouth', 'Neon', 1996, 24);
insert into voitures (id, marque, modele, annee, garage_id) values (594, 'Nissan', 'Sentra', 2007, 73);
insert into voitures (id, marque, modele, annee, garage_id) values (595, 'Toyota', 'Supra', 1998, 13);
insert into voitures (id, marque, modele, annee, garage_id) values (596, 'Audi', 'S4', 2010, 36);
insert into voitures (id, marque, modele, annee, garage_id) values (597, 'Chevrolet', 'Blazer', 1997, 128);
insert into voitures (id, marque, modele, annee, garage_id) values (598, 'Maserati', 'Quattroporte', 2005, 2);
insert into voitures (id, marque, modele, annee, garage_id) values (599, 'Chevrolet', 'Express 3500', 2007, 67);
insert into voitures (id, marque, modele, annee, garage_id) values (600, 'Volvo', 'XC60', 2011, 133);
insert into voitures (id, marque, modele, annee, garage_id) values (601, 'Pontiac', 'LeMans', 1993, 34);
insert into voitures (id, marque, modele, annee, garage_id) values (602, 'Bentley', 'Continental Flying Spur', 2012, 131);
insert into voitures (id, marque, modele, annee, garage_id) values (603, 'Jeep', 'Grand Cherokee', 2006, 126);
insert into voitures (id, marque, modele, annee, garage_id) values (604, 'Kia', 'Sorento', 2013, 108);
insert into voitures (id, marque, modele, annee, garage_id) values (605, 'Mercedes-Benz', 'CLS-Class', 2008, 35);
insert into voitures (id, marque, modele, annee, garage_id) values (606, 'Chevrolet', 'Silverado 1500', 2011, 146);
insert into voitures (id, marque, modele, annee, garage_id) values (607, 'BMW', 'Z3', 1996, 23);
insert into voitures (id, marque, modele, annee, garage_id) values (608, 'Hyundai', 'Accent', 2011, 229);
insert into voitures (id, marque, modele, annee, garage_id) values (609, 'Austin', 'Mini Cooper', 1964, 9);
insert into voitures (id, marque, modele, annee, garage_id) values (610, 'Suzuki', 'Equator', 2010, 297);
insert into voitures (id, marque, modele, annee, garage_id) values (611, 'Mitsubishi', 'Lancer Evolution', 2008, 104);
insert into voitures (id, marque, modele, annee, garage_id) values (612, 'Ford', 'E-Series', 1993, 251);
insert into voitures (id, marque, modele, annee, garage_id) values (613, 'GMC', '1500 Club Coupe', 1999, 66);
insert into voitures (id, marque, modele, annee, garage_id) values (614, 'Dodge', 'Ram 3500', 2009, 143);
insert into voitures (id, marque, modele, annee, garage_id) values (615, 'Subaru', 'Outback', 2009, 85);
insert into voitures (id, marque, modele, annee, garage_id) values (616, 'Toyota', 'Camry', 1993, 20);
insert into voitures (id, marque, modele, annee, garage_id) values (617, 'Lincoln', 'MKX', 2012, 8);
insert into voitures (id, marque, modele, annee, garage_id) values (618, 'Volkswagen', 'GTI', 2001, 52);
insert into voitures (id, marque, modele, annee, garage_id) values (619, 'Audi', '5000CS', 1988, 219);
insert into voitures (id, marque, modele, annee, garage_id) values (620, 'Suzuki', 'SJ', 1995, 139);
insert into voitures (id, marque, modele, annee, garage_id) values (621, 'Mercedes-Benz', 'C-Class', 2000, 21);
insert into voitures (id, marque, modele, annee, garage_id) values (622, 'Kia', 'Sorento', 2007, 138);
insert into voitures (id, marque, modele, annee, garage_id) values (623, 'Kia', 'Optima', 2002, 139);
insert into voitures (id, marque, modele, annee, garage_id) values (624, 'GMC', 'Sierra 1500', 2007, 213);
insert into voitures (id, marque, modele, annee, garage_id) values (625, 'Toyota', 'Tacoma Xtra', 2004, 201);
insert into voitures (id, marque, modele, annee, garage_id) values (626, 'Lincoln', 'Continental', 1992, 63);
insert into voitures (id, marque, modele, annee, garage_id) values (627, 'Chevrolet', 'Corvette', 1963, 232);
insert into voitures (id, marque, modele, annee, garage_id) values (628, 'Maybach', '57', 2008, 41);
insert into voitures (id, marque, modele, annee, garage_id) values (629, 'Hyundai', 'Equus', 2011, 240);
insert into voitures (id, marque, modele, annee, garage_id) values (630, 'Volkswagen', 'Cabriolet', 1991, 228);
insert into voitures (id, marque, modele, annee, garage_id) values (631, 'Ford', 'Club Wagon', 1992, 258);
insert into voitures (id, marque, modele, annee, garage_id) values (632, 'Chevrolet', 'Corvette', 1968, 72);
insert into voitures (id, marque, modele, annee, garage_id) values (633, 'Dodge', 'Ram Van 3500', 1996, 291);
insert into voitures (id, marque, modele, annee, garage_id) values (634, 'Chevrolet', 'Uplander', 2007, 216);
insert into voitures (id, marque, modele, annee, garage_id) values (635, 'Scion', 'xD', 2012, 234);
insert into voitures (id, marque, modele, annee, garage_id) values (636, 'Chevrolet', '2500', 1998, 175);
insert into voitures (id, marque, modele, annee, garage_id) values (637, 'Volvo', 'C70', 2010, 39);
insert into voitures (id, marque, modele, annee, garage_id) values (638, 'Lexus', 'LS', 2007, 276);
insert into voitures (id, marque, modele, annee, garage_id) values (639, 'Nissan', 'Xterra', 2008, 162);
insert into voitures (id, marque, modele, annee, garage_id) values (640, 'Dodge', 'Durango', 1998, 280);
insert into voitures (id, marque, modele, annee, garage_id) values (641, 'Toyota', '4Runner', 2002, 208);
insert into voitures (id, marque, modele, annee, garage_id) values (642, 'Jaguar', 'XK Series', 2002, 100);
insert into voitures (id, marque, modele, annee, garage_id) values (643, 'Suzuki', 'Reno', 2007, 233);
insert into voitures (id, marque, modele, annee, garage_id) values (644, 'Dodge', 'Dakota', 1998, 200);
insert into voitures (id, marque, modele, annee, garage_id) values (645, 'BMW', '1 Series', 2012, 82);
insert into voitures (id, marque, modele, annee, garage_id) values (646, 'Dodge', 'Stratus', 2001, 297);
insert into voitures (id, marque, modele, annee, garage_id) values (647, 'BMW', '1 Series', 2008, 34);
insert into voitures (id, marque, modele, annee, garage_id) values (648, 'Infiniti', 'QX', 2005, 247);
insert into voitures (id, marque, modele, annee, garage_id) values (649, 'Suzuki', 'Reno', 2007, 46);
insert into voitures (id, marque, modele, annee, garage_id) values (650, 'Mitsubishi', 'Truck', 1988, 75);
insert into voitures (id, marque, modele, annee, garage_id) values (651, 'BMW', '7 Series', 2003, 78);
insert into voitures (id, marque, modele, annee, garage_id) values (652, 'Honda', 'Accord', 1989, 151);
insert into voitures (id, marque, modele, annee, garage_id) values (653, 'Oldsmobile', 'Ciera', 1992, 253);
insert into voitures (id, marque, modele, annee, garage_id) values (654, 'GMC', '3500', 1995, 245);
insert into voitures (id, marque, modele, annee, garage_id) values (655, 'Saab', '9-2X', 2006, 234);
insert into voitures (id, marque, modele, annee, garage_id) values (656, 'Toyota', 'Avalon', 1997, 15);
insert into voitures (id, marque, modele, annee, garage_id) values (657, 'Chevrolet', 'Silverado 2500', 2002, 295);
insert into voitures (id, marque, modele, annee, garage_id) values (658, 'Hummer', 'H1', 2002, 261);
insert into voitures (id, marque, modele, annee, garage_id) values (659, 'Maybach', '57', 2005, 78);
insert into voitures (id, marque, modele, annee, garage_id) values (660, 'Ford', 'F-Series', 1996, 82);
insert into voitures (id, marque, modele, annee, garage_id) values (661, 'Mercury', 'Mariner', 2005, 32);
insert into voitures (id, marque, modele, annee, garage_id) values (662, 'Jeep', 'Grand Cherokee', 2009, 276);
insert into voitures (id, marque, modele, annee, garage_id) values (663, 'Cadillac', 'SRX', 2009, 31);
insert into voitures (id, marque, modele, annee, garage_id) values (664, 'Saab', '9-3', 2008, 162);
insert into voitures (id, marque, modele, annee, garage_id) values (665, 'Chevrolet', 'Silverado 2500', 2004, 13);
insert into voitures (id, marque, modele, annee, garage_id) values (666, 'Chevrolet', 'Malibu', 2000, 4);
insert into voitures (id, marque, modele, annee, garage_id) values (667, 'Mazda', 'RX-8', 2005, 31);
insert into voitures (id, marque, modele, annee, garage_id) values (668, 'Honda', 'Pilot', 2006, 63);
insert into voitures (id, marque, modele, annee, garage_id) values (669, 'GMC', '1500 Club Coupe', 1998, 48);
insert into voitures (id, marque, modele, annee, garage_id) values (670, 'Toyota', 'Highlander', 2010, 115);
insert into voitures (id, marque, modele, annee, garage_id) values (671, 'Volkswagen', 'Golf', 1988, 211);
insert into voitures (id, marque, modele, annee, garage_id) values (672, 'Geo', 'Metro', 1993, 171);
insert into voitures (id, marque, modele, annee, garage_id) values (673, 'GMC', 'Envoy', 2009, 19);
insert into voitures (id, marque, modele, annee, garage_id) values (674, 'Ford', 'Ranger', 1984, 28);
insert into voitures (id, marque, modele, annee, garage_id) values (675, 'Kia', 'Amanti', 2008, 79);
insert into voitures (id, marque, modele, annee, garage_id) values (676, 'Toyota', 'Prius Plug-in Hybrid', 2012, 40);
insert into voitures (id, marque, modele, annee, garage_id) values (677, 'Chevrolet', 'SSR', 2005, 66);
insert into voitures (id, marque, modele, annee, garage_id) values (678, 'Cadillac', 'Brougham', 1992, 206);
insert into voitures (id, marque, modele, annee, garage_id) values (679, 'Mazda', 'Navajo', 1991, 36);
insert into voitures (id, marque, modele, annee, garage_id) values (680, 'Pontiac', 'G3', 2009, 34);
insert into voitures (id, marque, modele, annee, garage_id) values (681, 'BMW', '5 Series', 2011, 55);
insert into voitures (id, marque, modele, annee, garage_id) values (682, 'Pontiac', 'Firebird Trans Am', 1986, 16);
insert into voitures (id, marque, modele, annee, garage_id) values (683, 'GMC', '3500', 1996, 139);
insert into voitures (id, marque, modele, annee, garage_id) values (684, 'BMW', '7 Series', 2010, 273);
insert into voitures (id, marque, modele, annee, garage_id) values (685, 'Oldsmobile', 'Intrigue', 2000, 231);
insert into voitures (id, marque, modele, annee, garage_id) values (686, 'GMC', 'Yukon', 1994, 153);
insert into voitures (id, marque, modele, annee, garage_id) values (687, 'Lotus', 'Esprit', 1987, 70);
insert into voitures (id, marque, modele, annee, garage_id) values (688, 'Mitsubishi', 'Challenger', 1999, 1);
insert into voitures (id, marque, modele, annee, garage_id) values (689, 'Honda', 'Element', 2008, 74);
insert into voitures (id, marque, modele, annee, garage_id) values (690, 'Ford', 'F350', 2000, 279);
insert into voitures (id, marque, modele, annee, garage_id) values (691, 'Oldsmobile', 'Intrigue', 2000, 120);
insert into voitures (id, marque, modele, annee, garage_id) values (692, 'Pontiac', 'G8', 2008, 233);
insert into voitures (id, marque, modele, annee, garage_id) values (693, 'Mercury', 'Sable', 1995, 245);
insert into voitures (id, marque, modele, annee, garage_id) values (694, 'Mazda', 'Mazda2', 2011, 27);
insert into voitures (id, marque, modele, annee, garage_id) values (695, 'Audi', 'Quattro', 1994, 61);
insert into voitures (id, marque, modele, annee, garage_id) values (696, 'Mazda', 'Miata MX-5', 2008, 192);
insert into voitures (id, marque, modele, annee, garage_id) values (697, 'Honda', 'Element', 2011, 250);
insert into voitures (id, marque, modele, annee, garage_id) values (698, 'Nissan', 'Maxima', 1992, 238);
insert into voitures (id, marque, modele, annee, garage_id) values (699, 'Kia', 'Soul', 2011, 192);
insert into voitures (id, marque, modele, annee, garage_id) values (700, 'Mitsubishi', 'Galant', 1986, 180);
insert into voitures (id, marque, modele, annee, garage_id) values (701, 'Aston Martin', 'DB9', 2010, 103);
insert into voitures (id, marque, modele, annee, garage_id) values (702, 'Hyundai', 'Tiburon', 2008, 114);
insert into voitures (id, marque, modele, annee, garage_id) values (703, 'Volvo', 'S40', 2003, 218);
insert into voitures (id, marque, modele, annee, garage_id) values (704, 'Isuzu', 'i-Series', 2006, 89);
insert into voitures (id, marque, modele, annee, garage_id) values (705, 'GMC', '1500 Club Coupe', 1996, 240);
insert into voitures (id, marque, modele, annee, garage_id) values (706, 'Nissan', 'Pathfinder', 1998, 259);
insert into voitures (id, marque, modele, annee, garage_id) values (707, 'Mercedes-Benz', 'S-Class', 1990, 84);
insert into voitures (id, marque, modele, annee, garage_id) values (708, 'Mercedes-Benz', 'R-Class', 2011, 52);
insert into voitures (id, marque, modele, annee, garage_id) values (709, 'GMC', 'Sierra 3500', 2005, 279);
insert into voitures (id, marque, modele, annee, garage_id) values (710, 'BMW', '745', 2005, 135);
insert into voitures (id, marque, modele, annee, garage_id) values (711, 'Mercedes-Benz', 'GLK-Class', 2012, 117);
insert into voitures (id, marque, modele, annee, garage_id) values (712, 'Mitsubishi', 'Truck', 1987, 69);
insert into voitures (id, marque, modele, annee, garage_id) values (713, 'Dodge', 'Grand Caravan', 2011, 73);
insert into voitures (id, marque, modele, annee, garage_id) values (714, 'Toyota', 'Land Cruiser', 2003, 295);
insert into voitures (id, marque, modele, annee, garage_id) values (715, 'Toyota', 'Highlander', 2003, 133);
insert into voitures (id, marque, modele, annee, garage_id) values (716, 'Toyota', 'Tercel', 1992, 126);
insert into voitures (id, marque, modele, annee, garage_id) values (717, 'Honda', 'Fit', 2008, 96);
insert into voitures (id, marque, modele, annee, garage_id) values (718, 'Volvo', 'V50', 2006, 300);
insert into voitures (id, marque, modele, annee, garage_id) values (719, 'Chevrolet', 'SSR', 2004, 184);
insert into voitures (id, marque, modele, annee, garage_id) values (720, 'Pontiac', 'Sunfire', 2003, 277);
insert into voitures (id, marque, modele, annee, garage_id) values (721, 'Honda', 'Civic GX', 2003, 163);
insert into voitures (id, marque, modele, annee, garage_id) values (722, 'Porsche', '944', 1983, 10);
insert into voitures (id, marque, modele, annee, garage_id) values (723, 'Volkswagen', 'GTI', 2006, 242);
insert into voitures (id, marque, modele, annee, garage_id) values (724, 'Toyota', 'Land Cruiser', 1995, 201);
insert into voitures (id, marque, modele, annee, garage_id) values (725, 'Ford', 'Laser', 1986, 196);
insert into voitures (id, marque, modele, annee, garage_id) values (726, 'Toyota', 'Tundra', 2005, 118);
insert into voitures (id, marque, modele, annee, garage_id) values (727, 'Pontiac', 'Fiero', 1984, 137);
insert into voitures (id, marque, modele, annee, garage_id) values (728, 'Nissan', 'Murano', 2006, 100);
insert into voitures (id, marque, modele, annee, garage_id) values (729, 'Honda', 'S2000', 2003, 68);
insert into voitures (id, marque, modele, annee, garage_id) values (730, 'Dodge', 'Avenger', 2011, 32);
insert into voitures (id, marque, modele, annee, garage_id) values (731, 'Nissan', 'Altima', 1996, 291);
insert into voitures (id, marque, modele, annee, garage_id) values (732, 'BMW', '3 Series', 2008, 233);
insert into voitures (id, marque, modele, annee, garage_id) values (733, 'Mazda', 'CX-9', 2011, 116);
insert into voitures (id, marque, modele, annee, garage_id) values (734, 'Chevrolet', 'Camaro', 1995, 137);
insert into voitures (id, marque, modele, annee, garage_id) values (735, 'Mazda', 'MX-6', 1989, 96);
insert into voitures (id, marque, modele, annee, garage_id) values (736, 'GMC', 'Rally Wagon 3500', 1993, 66);
insert into voitures (id, marque, modele, annee, garage_id) values (737, 'Honda', 'Civic', 1994, 33);
insert into voitures (id, marque, modele, annee, garage_id) values (738, 'Infiniti', 'QX', 2000, 232);
insert into voitures (id, marque, modele, annee, garage_id) values (739, 'Hyundai', 'Tiburon', 2003, 218);
insert into voitures (id, marque, modele, annee, garage_id) values (740, 'Ford', 'Tempo', 1994, 52);
insert into voitures (id, marque, modele, annee, garage_id) values (741, 'Hummer', 'H2', 2007, 3);
insert into voitures (id, marque, modele, annee, garage_id) values (742, 'Pontiac', 'Firefly', 1986, 211);
insert into voitures (id, marque, modele, annee, garage_id) values (743, 'Mercury', 'Topaz', 1992, 131);
insert into voitures (id, marque, modele, annee, garage_id) values (744, 'GMC', 'Yukon XL 2500', 2002, 140);
insert into voitures (id, marque, modele, annee, garage_id) values (745, 'Suzuki', 'Kizashi', 2012, 268);
insert into voitures (id, marque, modele, annee, garage_id) values (746, 'Lexus', 'ES', 1990, 268);
insert into voitures (id, marque, modele, annee, garage_id) values (747, 'GMC', '1500', 1998, 171);
insert into voitures (id, marque, modele, annee, garage_id) values (748, 'Cadillac', 'STS-V', 2008, 63);
insert into voitures (id, marque, modele, annee, garage_id) values (749, 'Mercury', 'Mountaineer', 2002, 297);
insert into voitures (id, marque, modele, annee, garage_id) values (750, 'Mitsubishi', 'Pajero', 1999, 243);
